# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: implant/implantpb/module.proto
# plugin: python-betterproto2
# This file has been @generated

__all__ = (
    "Ack",
    "Addon",
    "Addons",
    "BinaryResponse",
    "Block",
    "BypassRequest",
    "ChownRequest",
    "CurlRequest",
    "DownloadRequest",
    "DownloadResponse",
    "ExecRequest",
    "ExecResponse",
    "ExecuteAddon",
    "ExecuteBinary",
    "ExecuteCommand",
    "FFmpegRequest",
    "FileInfo",
    "GetSystem",
    "IfconfigResponse",
    "Init",
    "Inject",
    "KeyExchangeRequest",
    "KeyExchangeResponse",
    "LoadAddon",
    "LoadModule",
    "LsResponse",
    "Modules",
    "NetInterface",
    "NetstatResponse",
    "Os",
    "Ping",
    "Pipe",
    "PipeRequest",
    "Process",
    "PsResponse",
    "Register",
    "Registry",
    "RegistryRequest",
    "RegistryWriteRequest",
    "Request",
    "Response",
    "RunAsRequest",
    "SacrificeProcess",
    "Secure",
    "Service",
    "ServiceConfig",
    "ServiceRequest",
    "ServiceStatus",
    "ServicesResponse",
    "ShellRequest",
    "ShellResponse",
    "SockTabEntry",
    "Suicide",
    "Switch",
    "SysInfo",
    "TaskCtrl",
    "TaskInfo",
    "TaskListResponse",
    "TaskSchedule",
    "TaskScheduleRequest",
    "TaskSchedulesResponse",
    "Timer",
    "UploadRequest",
    "WmiMethodRequest",
    "WmiQueryRequest",
)

import typing

import betterproto2
import pydantic
from pydantic.dataclasses import dataclass

from ..message_pool import default_message_pool

_COMPILER_VERSION = "0.8.0"
betterproto2.check_compiler_version(_COMPILER_VERSION)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class Ack(betterproto2.Message):
    id: "typing.Annotated[int, pydantic.Field(ge=0, le=2**32 - 1)]" = (
        betterproto2.field(1, betterproto2.TYPE_UINT32)
    )

    success: "bool" = betterproto2.field(2, betterproto2.TYPE_BOOL)

    end: "bool" = betterproto2.field(3, betterproto2.TYPE_BOOL)


default_message_pool.register_message("modulepb", "ACK", Ack)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class Addon(betterproto2.Message):
    name: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        1, betterproto2.TYPE_STRING
    )

    type: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        2, betterproto2.TYPE_STRING
    )

    depend: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        3, betterproto2.TYPE_STRING
    )


default_message_pool.register_message("modulepb", "Addon", Addon)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class Addons(betterproto2.Message):
    addons: "list[Addon]" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, repeated=True
    )


default_message_pool.register_message("modulepb", "Addons", Addons)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class BinaryResponse(betterproto2.Message):
    data: "bytes" = betterproto2.field(1, betterproto2.TYPE_BYTES)
    """
    common return, bof BeaconOutput
    """

    message: "bytes" = betterproto2.field(2, betterproto2.TYPE_BYTES)
    """
    bof BeaconPrintf
    """

    err: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        4, betterproto2.TYPE_STRING
    )

    status: "typing.Annotated[int, pydantic.Field(ge=-2**31, le=2**31 - 1)]" = (
        betterproto2.field(3, betterproto2.TYPE_INT32)
    )


default_message_pool.register_message("modulepb", "BinaryResponse", BinaryResponse)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class Block(betterproto2.Message):
    block_id: "typing.Annotated[int, pydantic.Field(ge=0, le=2**32 - 1)]" = (
        betterproto2.field(1, betterproto2.TYPE_UINT32)
    )

    content: "bytes" = betterproto2.field(2, betterproto2.TYPE_BYTES)

    end: "bool" = betterproto2.field(3, betterproto2.TYPE_BOOL)


default_message_pool.register_message("modulepb", "Block", Block)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class BypassRequest(betterproto2.Message):
    etw: "bool" = betterproto2.field(1, betterproto2.TYPE_BOOL)

    amsi: "bool" = betterproto2.field(2, betterproto2.TYPE_BOOL)

    block_dll: "bool" = betterproto2.field(3, betterproto2.TYPE_BOOL)


default_message_pool.register_message("modulepb", "BypassRequest", BypassRequest)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class ChownRequest(betterproto2.Message):
    path: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        1, betterproto2.TYPE_STRING
    )

    uid: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        2, betterproto2.TYPE_STRING
    )

    gid: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        3, betterproto2.TYPE_STRING
    )

    recursive: "bool" = betterproto2.field(4, betterproto2.TYPE_BOOL)


default_message_pool.register_message("modulepb", "ChownRequest", ChownRequest)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class CurlRequest(betterproto2.Message):
    url: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        1, betterproto2.TYPE_STRING
    )

    timeout: "typing.Annotated[int, pydantic.Field(ge=-2**31, le=2**31 - 1)]" = (
        betterproto2.field(2, betterproto2.TYPE_INT32)
    )

    method: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        3, betterproto2.TYPE_STRING
    )

    body: "bytes" = betterproto2.field(4, betterproto2.TYPE_BYTES)

    header: "dict[str, str]" = betterproto2.field(
        5,
        betterproto2.TYPE_MAP,
        map_meta=betterproto2.map_meta(
            betterproto2.TYPE_STRING, betterproto2.TYPE_STRING
        ),
    )

    hostname: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        6, betterproto2.TYPE_STRING
    )


default_message_pool.register_message("modulepb", "CurlRequest", CurlRequest)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class DownloadRequest(betterproto2.Message):
    path: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        1, betterproto2.TYPE_STRING
    )

    name: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        2, betterproto2.TYPE_STRING
    )

    buffer_size: "typing.Annotated[int, pydantic.Field(ge=0, le=2**32 - 1)]" = (
        betterproto2.field(3, betterproto2.TYPE_UINT32)
    )

    dir: "bool" = betterproto2.field(4, betterproto2.TYPE_BOOL)

    cur: "typing.Annotated[int, pydantic.Field(ge=-2**31, le=2**31 - 1)]" = (
        betterproto2.field(5, betterproto2.TYPE_INT32)
    )


default_message_pool.register_message("modulepb", "DownloadRequest", DownloadRequest)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class DownloadResponse(betterproto2.Message):
    checksum: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        1, betterproto2.TYPE_STRING
    )

    size: "typing.Annotated[int, pydantic.Field(ge=0, le=2**64 - 1)]" = (
        betterproto2.field(2, betterproto2.TYPE_UINT64)
    )

    cur: "typing.Annotated[int, pydantic.Field(ge=-2**31, le=2**31 - 1)]" = (
        betterproto2.field(3, betterproto2.TYPE_INT32)
    )

    content: "bytes" = betterproto2.field(4, betterproto2.TYPE_BYTES)


default_message_pool.register_message("modulepb", "DownloadResponse", DownloadResponse)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class ExecRequest(betterproto2.Message):
    path: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        1, betterproto2.TYPE_STRING
    )

    args: "list[typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]]" = betterproto2.field(
        2, betterproto2.TYPE_STRING, repeated=True
    )

    output: "bool" = betterproto2.field(3, betterproto2.TYPE_BOOL)

    singleton: "bool" = betterproto2.field(4, betterproto2.TYPE_BOOL)

    realtime: "bool" = betterproto2.field(5, betterproto2.TYPE_BOOL)

    ppid: "typing.Annotated[int, pydantic.Field(ge=0, le=2**32 - 1)]" = (
        betterproto2.field(10, betterproto2.TYPE_UINT32)
    )


default_message_pool.register_message("modulepb", "ExecRequest", ExecRequest)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class ExecResponse(betterproto2.Message):
    status_code: "typing.Annotated[int, pydantic.Field(ge=-2**31, le=2**31 - 1)]" = (
        betterproto2.field(1, betterproto2.TYPE_INT32)
    )

    stdout: "bytes" = betterproto2.field(2, betterproto2.TYPE_BYTES)

    stderr: "bytes" = betterproto2.field(3, betterproto2.TYPE_BYTES)

    pid: "typing.Annotated[int, pydantic.Field(ge=0, le=2**32 - 1)]" = (
        betterproto2.field(4, betterproto2.TYPE_UINT32)
    )

    end: "bool" = betterproto2.field(5, betterproto2.TYPE_BOOL)


default_message_pool.register_message("modulepb", "ExecResponse", ExecResponse)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class ExecuteAddon(betterproto2.Message):
    addon: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        1, betterproto2.TYPE_STRING
    )

    execute_binary: "ExecuteBinary | None" = betterproto2.field(
        2, betterproto2.TYPE_MESSAGE, optional=True
    )


default_message_pool.register_message("modulepb", "ExecuteAddon", ExecuteAddon)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class ExecuteBinary(betterproto2.Message):
    name: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        1, betterproto2.TYPE_STRING
    )

    bin: "bytes" = betterproto2.field(2, betterproto2.TYPE_BYTES)

    param: "dict[str, str]" = betterproto2.field(
        3,
        betterproto2.TYPE_MAP,
        map_meta=betterproto2.map_meta(
            betterproto2.TYPE_STRING, betterproto2.TYPE_STRING
        ),
    )

    type: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        4, betterproto2.TYPE_STRING
    )

    process_name: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        5, betterproto2.TYPE_STRING
    )

    args: "list[typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]]" = betterproto2.field(
        6, betterproto2.TYPE_STRING, repeated=True
    )

    entry_point: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        7, betterproto2.TYPE_STRING
    )

    data: "bytes" = betterproto2.field(8, betterproto2.TYPE_BYTES)

    output: "bool" = betterproto2.field(9, betterproto2.TYPE_BOOL)

    arch: "typing.Annotated[int, pydantic.Field(ge=0, le=2**32 - 1)]" = (
        betterproto2.field(10, betterproto2.TYPE_UINT32)
    )

    timeout: "typing.Annotated[int, pydantic.Field(ge=0, le=2**32 - 1)]" = (
        betterproto2.field(11, betterproto2.TYPE_UINT32)
    )

    sacrifice: "SacrificeProcess | None" = betterproto2.field(
        12, betterproto2.TYPE_MESSAGE, optional=True
    )

    path: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        13, betterproto2.TYPE_STRING
    )

    context: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        14, betterproto2.TYPE_STRING
    )

    delay: "typing.Annotated[int, pydantic.Field(ge=0, le=2**32 - 1)]" = (
        betterproto2.field(15, betterproto2.TYPE_UINT32)
    )
    """
    millisecond
    """


default_message_pool.register_message("modulepb", "ExecuteBinary", ExecuteBinary)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class ExecuteCommand(betterproto2.Message):
    command: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        1, betterproto2.TYPE_STRING
    )

    sacrifice: "SacrificeProcess | None" = betterproto2.field(
        2, betterproto2.TYPE_MESSAGE, optional=True
    )


default_message_pool.register_message("modulepb", "ExecuteCommand", ExecuteCommand)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class FFmpegRequest(betterproto2.Message):
    action: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        1, betterproto2.TYPE_STRING
    )

    device_name: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        2, betterproto2.TYPE_STRING
    )

    output_format: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        3, betterproto2.TYPE_STRING
    )

    output_path: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        4, betterproto2.TYPE_STRING
    )

    time: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        5, betterproto2.TYPE_STRING
    )


default_message_pool.register_message("modulepb", "FFmpegRequest", FFmpegRequest)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class FileInfo(betterproto2.Message):
    name: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        1, betterproto2.TYPE_STRING
    )

    is_dir: "bool" = betterproto2.field(2, betterproto2.TYPE_BOOL)

    size: "typing.Annotated[int, pydantic.Field(ge=0, le=2**64 - 1)]" = (
        betterproto2.field(3, betterproto2.TYPE_UINT64)
    )

    mod_time: "typing.Annotated[int, pydantic.Field(ge=-2**63, le=2**63 - 1)]" = (
        betterproto2.field(4, betterproto2.TYPE_INT64)
    )

    mode: "typing.Annotated[int, pydantic.Field(ge=0, le=2**32 - 1)]" = (
        betterproto2.field(5, betterproto2.TYPE_UINT32)
    )

    link: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        6, betterproto2.TYPE_STRING
    )


default_message_pool.register_message("modulepb", "FileInfo", FileInfo)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class GetSystem(betterproto2.Message):
    bin: "bytes" = betterproto2.field(1, betterproto2.TYPE_BYTES)

    pid: "typing.Annotated[int, pydantic.Field(ge=0, le=2**32 - 1)]" = (
        betterproto2.field(2, betterproto2.TYPE_UINT32)
    )


default_message_pool.register_message("modulepb", "GetSystem", GetSystem)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class IfconfigResponse(betterproto2.Message):
    net_interfaces: "list[NetInterface]" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, repeated=True
    )


default_message_pool.register_message("modulepb", "IfconfigResponse", IfconfigResponse)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class Init(betterproto2.Message):
    data: "bytes" = betterproto2.field(1, betterproto2.TYPE_BYTES)


default_message_pool.register_message("modulepb", "Init", Init)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class Inject(betterproto2.Message):
    bin: "bytes" = betterproto2.field(1, betterproto2.TYPE_BYTES)

    pid: "typing.Annotated[int, pydantic.Field(ge=0, le=2**32 - 1)]" = (
        betterproto2.field(2, betterproto2.TYPE_UINT32)
    )


default_message_pool.register_message("modulepb", "Inject", Inject)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class KeyExchangeRequest(betterproto2.Message):
    """
    Age 密钥交换相关消息
    """

    public_key: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        1, betterproto2.TYPE_STRING
    )
    """
    临时公钥 (Age X25519)
    """

    signature: "bytes" = betterproto2.field(2, betterproto2.TYPE_BYTES)
    """
    对临时公钥的签名
    """

    timestamp: "typing.Annotated[int, pydantic.Field(ge=0, le=2**64 - 1)]" = (
        betterproto2.field(3, betterproto2.TYPE_UINT64)
    )
    """
    时间戳
    """

    nonce: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        4, betterproto2.TYPE_STRING
    )
    """
    随机数
    """


default_message_pool.register_message(
    "modulepb", "KeyExchangeRequest", KeyExchangeRequest
)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class KeyExchangeResponse(betterproto2.Message):
    public_key: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        1, betterproto2.TYPE_STRING
    )
    """
    Server 临时公钥
    """


default_message_pool.register_message(
    "modulepb", "KeyExchangeResponse", KeyExchangeResponse
)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class LoadAddon(betterproto2.Message):
    name: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        1, betterproto2.TYPE_STRING
    )

    type: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        2, betterproto2.TYPE_STRING
    )

    depend: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        3, betterproto2.TYPE_STRING
    )

    bin: "bytes" = betterproto2.field(4, betterproto2.TYPE_BYTES)


default_message_pool.register_message("modulepb", "LoadAddon", LoadAddon)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class LoadModule(betterproto2.Message):
    bundle: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        1, betterproto2.TYPE_STRING
    )

    bin: "bytes" = betterproto2.field(2, betterproto2.TYPE_BYTES)


default_message_pool.register_message("modulepb", "LoadModule", LoadModule)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class LsResponse(betterproto2.Message):
    path: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        1, betterproto2.TYPE_STRING
    )

    exists: "bool" = betterproto2.field(2, betterproto2.TYPE_BOOL)

    files: "list[FileInfo]" = betterproto2.field(
        3, betterproto2.TYPE_MESSAGE, repeated=True
    )


default_message_pool.register_message("modulepb", "LsResponse", LsResponse)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class Modules(betterproto2.Message):
    modules: "list[typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]]" = betterproto2.field(
        1, betterproto2.TYPE_STRING, repeated=True
    )


default_message_pool.register_message("modulepb", "Modules", Modules)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class NetInterface(betterproto2.Message):
    index: "typing.Annotated[int, pydantic.Field(ge=-2**31, le=2**31 - 1)]" = (
        betterproto2.field(1, betterproto2.TYPE_INT32)
    )

    name: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        2, betterproto2.TYPE_STRING
    )

    mac: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        3, betterproto2.TYPE_STRING
    )

    ip_addresses: "list[typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]]" = betterproto2.field(
        4, betterproto2.TYPE_STRING, repeated=True
    )


default_message_pool.register_message("modulepb", "NetInterface", NetInterface)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class NetstatResponse(betterproto2.Message):
    socks: "list[SockTabEntry]" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, repeated=True
    )


default_message_pool.register_message("modulepb", "NetstatResponse", NetstatResponse)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class Os(betterproto2.Message):
    name: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        1, betterproto2.TYPE_STRING
    )

    version: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        2, betterproto2.TYPE_STRING
    )
    """
    kernel version
    """

    release: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        3, betterproto2.TYPE_STRING
    )
    """
    release version
    """

    arch: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        4, betterproto2.TYPE_STRING
    )

    username: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        5, betterproto2.TYPE_STRING
    )

    hostname: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        6, betterproto2.TYPE_STRING
    )

    locale: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        7, betterproto2.TYPE_STRING
    )
    """
    timezone
    """


default_message_pool.register_message("modulepb", "Os", Os)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class Ping(betterproto2.Message):
    nonce: "typing.Annotated[int, pydantic.Field(ge=-2**31, le=2**31 - 1)]" = (
        betterproto2.field(1, betterproto2.TYPE_INT32)
    )


default_message_pool.register_message("modulepb", "Ping", Ping)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class Pipe(betterproto2.Message):
    name: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        1, betterproto2.TYPE_STRING
    )

    target: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        2, betterproto2.TYPE_STRING
    )

    data: "bytes" = betterproto2.field(4, betterproto2.TYPE_BYTES)


default_message_pool.register_message("modulepb", "Pipe", Pipe)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class PipeRequest(betterproto2.Message):
    type: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        1, betterproto2.TYPE_STRING
    )

    pipe: "Pipe | None" = betterproto2.field(
        2, betterproto2.TYPE_MESSAGE, optional=True
    )


default_message_pool.register_message("modulepb", "PipeRequest", PipeRequest)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class Process(betterproto2.Message):
    name: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        1, betterproto2.TYPE_STRING
    )

    pid: "typing.Annotated[int, pydantic.Field(ge=0, le=2**32 - 1)]" = (
        betterproto2.field(2, betterproto2.TYPE_UINT32)
    )

    ppid: "typing.Annotated[int, pydantic.Field(ge=0, le=2**32 - 1)]" = (
        betterproto2.field(3, betterproto2.TYPE_UINT32)
    )

    owner: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        4, betterproto2.TYPE_STRING
    )

    arch: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        5, betterproto2.TYPE_STRING
    )

    path: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        6, betterproto2.TYPE_STRING
    )

    args: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        7, betterproto2.TYPE_STRING
    )

    uid: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        8, betterproto2.TYPE_STRING
    )


default_message_pool.register_message("modulepb", "Process", Process)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class PsResponse(betterproto2.Message):
    processes: "list[Process]" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, repeated=True
    )


default_message_pool.register_message("modulepb", "PsResponse", PsResponse)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class Register(betterproto2.Message):
    name: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        1, betterproto2.TYPE_STRING
    )

    proxy: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        2, betterproto2.TYPE_STRING
    )

    module: "list[typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]]" = betterproto2.field(
        3, betterproto2.TYPE_STRING, repeated=True
    )

    addons: "list[Addon]" = betterproto2.field(
        4, betterproto2.TYPE_MESSAGE, repeated=True
    )

    timer: "Timer | None" = betterproto2.field(
        5, betterproto2.TYPE_MESSAGE, optional=True
    )

    sysinfo: "SysInfo | None" = betterproto2.field(
        11, betterproto2.TYPE_MESSAGE, optional=True
    )

    secure: "Secure | None" = betterproto2.field(
        12, betterproto2.TYPE_MESSAGE, optional=True
    )
    """
    implant的公钥，用于server加密数据
    """


default_message_pool.register_message("modulepb", "Register", Register)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class Registry(betterproto2.Message):
    hive: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        1, betterproto2.TYPE_STRING
    )

    path: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        2, betterproto2.TYPE_STRING
    )

    key: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        3, betterproto2.TYPE_STRING
    )


default_message_pool.register_message("modulepb", "Registry", Registry)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class RegistryRequest(betterproto2.Message):
    """
    wrap for client
    """

    type: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        1, betterproto2.TYPE_STRING
    )

    registry: "Registry | None" = betterproto2.field(
        2, betterproto2.TYPE_MESSAGE, optional=True
    )


default_message_pool.register_message("modulepb", "RegistryRequest", RegistryRequest)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class RegistryWriteRequest(betterproto2.Message):
    hive: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        1, betterproto2.TYPE_STRING
    )

    path: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        2, betterproto2.TYPE_STRING
    )

    key: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        3, betterproto2.TYPE_STRING
    )

    string_value: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        5, betterproto2.TYPE_STRING
    )

    byte_value: "bytes" = betterproto2.field(6, betterproto2.TYPE_BYTES)

    dword_value: "typing.Annotated[int, pydantic.Field(ge=0, le=2**32 - 1)]" = (
        betterproto2.field(7, betterproto2.TYPE_UINT32)
    )

    qword_value: "typing.Annotated[int, pydantic.Field(ge=0, le=2**64 - 1)]" = (
        betterproto2.field(8, betterproto2.TYPE_UINT64)
    )

    regtype: "typing.Annotated[int, pydantic.Field(ge=0, le=2**32 - 1)]" = (
        betterproto2.field(10, betterproto2.TYPE_UINT32)
    )


default_message_pool.register_message(
    "modulepb", "RegistryWriteRequest", RegistryWriteRequest
)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class Request(betterproto2.Message):
    """
    common empty request
    """

    name: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        1, betterproto2.TYPE_STRING
    )

    input: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        2, betterproto2.TYPE_STRING
    )

    args: "list[typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]]" = betterproto2.field(
        3, betterproto2.TYPE_STRING, repeated=True
    )

    params: "dict[str, str]" = betterproto2.field(
        4,
        betterproto2.TYPE_MAP,
        map_meta=betterproto2.map_meta(
            betterproto2.TYPE_STRING, betterproto2.TYPE_STRING
        ),
    )

    bin: "bytes" = betterproto2.field(5, betterproto2.TYPE_BYTES)


default_message_pool.register_message("modulepb", "Request", Request)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class Response(betterproto2.Message):
    output: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        1, betterproto2.TYPE_STRING
    )

    error: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        2, betterproto2.TYPE_STRING
    )

    kv: "dict[str, str]" = betterproto2.field(
        3,
        betterproto2.TYPE_MAP,
        map_meta=betterproto2.map_meta(
            betterproto2.TYPE_STRING, betterproto2.TYPE_STRING
        ),
    )

    array: "list[typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]]" = betterproto2.field(
        4, betterproto2.TYPE_STRING, repeated=True
    )


default_message_pool.register_message("modulepb", "Response", Response)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class RunAsRequest(betterproto2.Message):
    username: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        1, betterproto2.TYPE_STRING
    )
    """
    需要执行的用户名
    """

    domain: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        2, betterproto2.TYPE_STRING
    )
    """
    用户所属域
    """

    password: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        3, betterproto2.TYPE_STRING
    )
    """
    用户密码
    """

    program: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        4, betterproto2.TYPE_STRING
    )
    """
    程序路径
    """

    args: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        5, betterproto2.TYPE_STRING
    )
    """
    程序参数（可选）
    """

    use_profile: "bool" = betterproto2.field(6, betterproto2.TYPE_BOOL)

    netonly: "bool" = betterproto2.field(7, betterproto2.TYPE_BOOL)
    """
    是否仅使用网络凭据 (可选，默认 false)
    """

    use_env: "bool" = betterproto2.field(8, betterproto2.TYPE_BOOL)


default_message_pool.register_message("modulepb", "RunAsRequest", RunAsRequest)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class SacrificeProcess(betterproto2.Message):
    hidden: "bool" = betterproto2.field(1, betterproto2.TYPE_BOOL)

    block_dll: "bool" = betterproto2.field(2, betterproto2.TYPE_BOOL)

    etw: "bool" = betterproto2.field(3, betterproto2.TYPE_BOOL)

    ppid: "typing.Annotated[int, pydantic.Field(ge=0, le=2**32 - 1)]" = (
        betterproto2.field(4, betterproto2.TYPE_UINT32)
    )

    argue: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        5, betterproto2.TYPE_STRING
    )


default_message_pool.register_message("modulepb", "SacrificeProcess", SacrificeProcess)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class Secure(betterproto2.Message):
    enable: "bool" = betterproto2.field(1, betterproto2.TYPE_BOOL)

    key: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        2, betterproto2.TYPE_STRING
    )
    """
    encryption key
    """

    type: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        3, betterproto2.TYPE_STRING
    )
    """
    encryption type
    """

    public_key: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        4, betterproto2.TYPE_STRING
    )
    """
    implant的公钥，用于server加密数据
    """


default_message_pool.register_message("modulepb", "Secure", Secure)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class Service(betterproto2.Message):
    config: "ServiceConfig | None" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, optional=True
    )

    status: "ServiceStatus | None" = betterproto2.field(
        2, betterproto2.TYPE_MESSAGE, optional=True
    )


default_message_pool.register_message("modulepb", "Service", Service)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class ServiceConfig(betterproto2.Message):
    name: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        1, betterproto2.TYPE_STRING
    )

    display_name: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        2, betterproto2.TYPE_STRING
    )

    executable_path: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        3, betterproto2.TYPE_STRING
    )

    start_type: "typing.Annotated[int, pydantic.Field(ge=0, le=2**32 - 1)]" = (
        betterproto2.field(4, betterproto2.TYPE_UINT32)
    )

    error_control: "typing.Annotated[int, pydantic.Field(ge=0, le=2**32 - 1)]" = (
        betterproto2.field(5, betterproto2.TYPE_UINT32)
    )

    account_name: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        6, betterproto2.TYPE_STRING
    )


default_message_pool.register_message("modulepb", "ServiceConfig", ServiceConfig)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class ServiceRequest(betterproto2.Message):
    """
    wrap for client
    """

    type: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        1, betterproto2.TYPE_STRING
    )

    service: "ServiceConfig | None" = betterproto2.field(
        2, betterproto2.TYPE_MESSAGE, optional=True
    )


default_message_pool.register_message("modulepb", "ServiceRequest", ServiceRequest)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class ServicesResponse(betterproto2.Message):
    services: "list[Service]" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, repeated=True
    )


default_message_pool.register_message("modulepb", "ServicesResponse", ServicesResponse)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class ServiceStatus(betterproto2.Message):
    current_state: "typing.Annotated[int, pydantic.Field(ge=0, le=2**32 - 1)]" = (
        betterproto2.field(1, betterproto2.TYPE_UINT32)
    )

    process_id: "typing.Annotated[int, pydantic.Field(ge=0, le=2**32 - 1)]" = (
        betterproto2.field(2, betterproto2.TYPE_UINT32)
    )

    exit_code: "typing.Annotated[int, pydantic.Field(ge=0, le=2**32 - 1)]" = (
        betterproto2.field(3, betterproto2.TYPE_UINT32)
    )

    checkpoint: "typing.Annotated[int, pydantic.Field(ge=0, le=2**32 - 1)]" = (
        betterproto2.field(4, betterproto2.TYPE_UINT32)
    )

    wait_hint: "typing.Annotated[int, pydantic.Field(ge=0, le=2**32 - 1)]" = (
        betterproto2.field(5, betterproto2.TYPE_UINT32)
    )


default_message_pool.register_message("modulepb", "ServiceStatus", ServiceStatus)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class ShellRequest(betterproto2.Message):
    """
    Shell/PTY 相关消息定义
    """

    type: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        1, betterproto2.TYPE_STRING
    )
    """
    操作类型: "start", "input", "stop"
    """

    session_id: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        2, betterproto2.TYPE_STRING
    )
    """
    会话ID
    """

    shell: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        3, betterproto2.TYPE_STRING
    )
    """
    shell类型: "/bin/bash", "cmd.exe", "powershell.exe" 等
    """

    cols: "typing.Annotated[int, pydantic.Field(ge=0, le=2**32 - 1)]" = (
        betterproto2.field(4, betterproto2.TYPE_UINT32)
    )
    """
    终端列数
    """

    rows: "typing.Annotated[int, pydantic.Field(ge=0, le=2**32 - 1)]" = (
        betterproto2.field(5, betterproto2.TYPE_UINT32)
    )
    """
    终端行数
    """

    input_data: "bytes" = betterproto2.field(6, betterproto2.TYPE_BYTES)
    """
    输入数据（二进制）
    """

    input_text: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        7, betterproto2.TYPE_STRING
    )
    """
    输入数据（文本）
    """

    params: "dict[str, str]" = betterproto2.field(
        8,
        betterproto2.TYPE_MAP,
        map_meta=betterproto2.map_meta(
            betterproto2.TYPE_STRING, betterproto2.TYPE_STRING
        ),
    )
    """
    额外参数
    """


default_message_pool.register_message("modulepb", "ShellRequest", ShellRequest)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class ShellResponse(betterproto2.Message):
    session_id: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        1, betterproto2.TYPE_STRING
    )
    """
    会话ID
    """

    output_data: "bytes" = betterproto2.field(2, betterproto2.TYPE_BYTES)
    """
    输出数据（二进制）
    """

    output_text: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        3, betterproto2.TYPE_STRING
    )
    """
    输出数据（文本）
    """

    error: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        4, betterproto2.TYPE_STRING
    )
    """
    错误信息
    """

    session_active: "bool" = betterproto2.field(5, betterproto2.TYPE_BOOL)
    """
    会话是否仍然活跃
    """

    active_sessions: "list[typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]]" = betterproto2.field(
        6, betterproto2.TYPE_STRING, repeated=True
    )

    metadata: "dict[str, str]" = betterproto2.field(
        7,
        betterproto2.TYPE_MAP,
        map_meta=betterproto2.map_meta(
            betterproto2.TYPE_STRING, betterproto2.TYPE_STRING
        ),
    )


default_message_pool.register_message("modulepb", "ShellResponse", ShellResponse)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class SockTabEntry(betterproto2.Message):
    local_addr: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        1, betterproto2.TYPE_STRING
    )

    remote_addr: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        2, betterproto2.TYPE_STRING
    )

    sk_state: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        3, betterproto2.TYPE_STRING
    )

    pid: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        5, betterproto2.TYPE_STRING
    )
    """
     uint32 uid = 4;
    """

    protocol: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        6, betterproto2.TYPE_STRING
    )


default_message_pool.register_message("modulepb", "SockTabEntry", SockTabEntry)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class Suicide(betterproto2.Message):
    type: "typing.Annotated[int, pydantic.Field(ge=-2**31, le=2**31 - 1)]" = (
        betterproto2.field(1, betterproto2.TYPE_INT32)
    )

    timestamp: "typing.Annotated[int, pydantic.Field(ge=-2**63, le=2**63 - 1)]" = (
        betterproto2.field(2, betterproto2.TYPE_INT64)
    )


default_message_pool.register_message("modulepb", "Suicide", Suicide)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class Switch(betterproto2.Message):
    urls: "list[typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]]" = betterproto2.field(
        1, betterproto2.TYPE_STRING, repeated=True
    )


default_message_pool.register_message("modulepb", "Switch", Switch)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class SysInfo(betterproto2.Message):
    filepath: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        1, betterproto2.TYPE_STRING
    )

    workdir: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        2, betterproto2.TYPE_STRING
    )

    is_privilege: "bool" = betterproto2.field(3, betterproto2.TYPE_BOOL)

    os: "Os | None" = betterproto2.field(11, betterproto2.TYPE_MESSAGE, optional=True)

    process: "Process | None" = betterproto2.field(
        12, betterproto2.TYPE_MESSAGE, optional=True
    )


default_message_pool.register_message("modulepb", "SysInfo", SysInfo)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class TaskCtrl(betterproto2.Message):
    task_id: "typing.Annotated[int, pydantic.Field(ge=0, le=2**32 - 1)]" = (
        betterproto2.field(1, betterproto2.TYPE_UINT32)
    )

    op: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        2, betterproto2.TYPE_STRING
    )


default_message_pool.register_message("modulepb", "TaskCtrl", TaskCtrl)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class TaskInfo(betterproto2.Message):
    task_id: "typing.Annotated[int, pydantic.Field(ge=0, le=2**32 - 1)]" = (
        betterproto2.field(1, betterproto2.TYPE_UINT32)
    )

    last: "typing.Annotated[int, pydantic.Field(ge=0, le=2**64 - 1)]" = (
        betterproto2.field(2, betterproto2.TYPE_UINT64)
    )

    recv_count: "typing.Annotated[int, pydantic.Field(ge=0, le=2**32 - 1)]" = (
        betterproto2.field(3, betterproto2.TYPE_UINT32)
    )

    send_count: "typing.Annotated[int, pydantic.Field(ge=0, le=2**32 - 1)]" = (
        betterproto2.field(4, betterproto2.TYPE_UINT32)
    )


default_message_pool.register_message("modulepb", "TaskInfo", TaskInfo)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class TaskListResponse(betterproto2.Message):
    tasks: "list[TaskInfo]" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, repeated=True
    )


default_message_pool.register_message("modulepb", "TaskListResponse", TaskListResponse)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class TaskSchedule(betterproto2.Message):
    name: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        1, betterproto2.TYPE_STRING
    )

    path: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        2, betterproto2.TYPE_STRING
    )

    executable_path: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        3, betterproto2.TYPE_STRING
    )

    trigger_type: "typing.Annotated[int, pydantic.Field(ge=0, le=2**32 - 1)]" = (
        betterproto2.field(4, betterproto2.TYPE_UINT32)
    )

    start_boundary: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        5, betterproto2.TYPE_STRING
    )

    description: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        6, betterproto2.TYPE_STRING
    )

    enabled: "bool" = betterproto2.field(7, betterproto2.TYPE_BOOL)

    last_run_time: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        8, betterproto2.TYPE_STRING
    )

    next_run_time: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        9, betterproto2.TYPE_STRING
    )


default_message_pool.register_message("modulepb", "TaskSchedule", TaskSchedule)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class TaskScheduleRequest(betterproto2.Message):
    type: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        1, betterproto2.TYPE_STRING
    )

    taskschd: "TaskSchedule | None" = betterproto2.field(
        2, betterproto2.TYPE_MESSAGE, optional=True
    )


default_message_pool.register_message(
    "modulepb", "TaskScheduleRequest", TaskScheduleRequest
)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class TaskSchedulesResponse(betterproto2.Message):
    schedules: "list[TaskSchedule]" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, repeated=True
    )


default_message_pool.register_message(
    "modulepb", "TaskSchedulesResponse", TaskSchedulesResponse
)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class Timer(betterproto2.Message):
    expression: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        1, betterproto2.TYPE_STRING
    )

    jitter: "float" = betterproto2.field(2, betterproto2.TYPE_DOUBLE)


default_message_pool.register_message("modulepb", "Timer", Timer)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class UploadRequest(betterproto2.Message):
    name: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        1, betterproto2.TYPE_STRING
    )

    target: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        2, betterproto2.TYPE_STRING
    )

    priv: "typing.Annotated[int, pydantic.Field(ge=0, le=2**32 - 1)]" = (
        betterproto2.field(3, betterproto2.TYPE_UINT32)
    )

    data: "bytes" = betterproto2.field(4, betterproto2.TYPE_BYTES)

    hidden: "bool" = betterproto2.field(5, betterproto2.TYPE_BOOL)

    override: "bool" = betterproto2.field(6, betterproto2.TYPE_BOOL)


default_message_pool.register_message("modulepb", "UploadRequest", UploadRequest)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class WmiMethodRequest(betterproto2.Message):
    namespace: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        1, betterproto2.TYPE_STRING
    )

    class_name: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        2, betterproto2.TYPE_STRING
    )

    method_name: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        3, betterproto2.TYPE_STRING
    )

    params: "dict[str, str]" = betterproto2.field(
        4,
        betterproto2.TYPE_MAP,
        map_meta=betterproto2.map_meta(
            betterproto2.TYPE_STRING, betterproto2.TYPE_STRING
        ),
    )


default_message_pool.register_message("modulepb", "WmiMethodRequest", WmiMethodRequest)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class WmiQueryRequest(betterproto2.Message):
    namespace: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        1, betterproto2.TYPE_STRING
    )

    args: "list[typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]]" = betterproto2.field(
        2, betterproto2.TYPE_STRING, repeated=True
    )


default_message_pool.register_message("modulepb", "WmiQueryRequest", WmiQueryRequest)
