# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: client/clientpb/client.proto
# plugin: python-betterproto2
# This file has been @generated

__all__ = (
    "Artifact",
    "Artifacts",
    "Audit",
    "Audits",
    "Basic",
    "BasicUpdateSession",
    "Bin",
    "BindPipeline",
    "BuildConfig",
    "BuildResources",
    "Cert",
    "CertificateSubject",
    "Certs",
    "Client",
    "Clients",
    "Context",
    "Contexts",
    "CtrlPipeline",
    "Dll2Shellcode",
    "DockerBuildConfig",
    "Empty",
    "Encryption",
    "Event",
    "Events",
    "Exe2Shellcode",
    "File",
    "Files",
    "GithubActionBuildConfig",
    "GithubWorkflow",
    "GithubWorkflowConfig",
    "GithubWorkflows",
    "HttpPipeline",
    "Int",
    "Job",
    "JobCtrl",
    "JobStatus",
    "Jobs",
    "KeyPair",
    "LicenseInfo",
    "Listener",
    "Listeners",
    "LoginReq",
    "Notify",
    "On",
    "Pipeline",
    "Pipelines",
    "Plugin",
    "Plugins",
    "Polling",
    "Profile",
    "Profiles",
    "RegisterListener",
    "RegisterSession",
    "Rem",
    "RemAgent",
    "RemAgents",
    "RemLog",
    "ResourceEntry",
    "SaasBuildConfig",
    "Secure",
    "Session",
    "SessionRequest",
    "Sessions",
    "ShellcodeEncode",
    "SpiteCache",
    "SpiteCacheItem",
    "SpiteRequest",
    "SpiteResponse",
    "Sync",
    "SyncResp",
    "Task",
    "TaskContext",
    "TaskContexts",
    "TaskDesc",
    "TaskDescs",
    "TaskRequest",
    "Tasks",
    "TasksContext",
    "TcpPipeline",
    "Tls",
    "WebContent",
    "WebContents",
    "Website",
    "Websites",
)

import typing

import betterproto2
import pydantic
from pydantic import model_validator
from pydantic.dataclasses import dataclass

from ..message_pool import default_message_pool

_COMPILER_VERSION = "0.9.0"
betterproto2.check_compiler_version(_COMPILER_VERSION)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class Artifact(betterproto2.Message):
    id: "typing.Annotated[int, pydantic.Field(ge=0, le=2**32 - 1)]" = (
        betterproto2.field(1, betterproto2.TYPE_UINT32)
    )

    bin: "bytes" = betterproto2.field(2, betterproto2.TYPE_BYTES)

    name: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        3, betterproto2.TYPE_STRING
    )

    type: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        4, betterproto2.TYPE_STRING
    )

    target: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        5, betterproto2.TYPE_STRING
    )

    arch: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        6, betterproto2.TYPE_STRING
    )

    platform: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        7, betterproto2.TYPE_STRING
    )

    profile: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        8, betterproto2.TYPE_STRING
    )

    pipeline: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        9, betterproto2.TYPE_STRING
    )

    format: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        10, betterproto2.TYPE_STRING
    )

    created_at: "typing.Annotated[int, pydantic.Field(ge=-2**63, le=2**63 - 1)]" = (
        betterproto2.field(11, betterproto2.TYPE_INT64)
    )

    status: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        12, betterproto2.TYPE_STRING
    )

    conclusion: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        13, betterproto2.TYPE_STRING
    )

    profile_bytes: "bytes" = betterproto2.field(14, betterproto2.TYPE_BYTES)

    params_bytes: "bytes" = betterproto2.field(15, betterproto2.TYPE_BYTES)

    source: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        16, betterproto2.TYPE_STRING
    )

    log: "bytes" = betterproto2.field(17, betterproto2.TYPE_BYTES)

    log_num: "typing.Annotated[int, pydantic.Field(ge=0, le=2**32 - 1)]" = (
        betterproto2.field(18, betterproto2.TYPE_UINT32)
    )

    rdi: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        19, betterproto2.TYPE_STRING
    )


default_message_pool.register_message("clientpb", "Artifact", Artifact)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class Artifacts(betterproto2.Message):
    artifacts: "list[Artifact]" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, repeated=True
    )


default_message_pool.register_message("clientpb", "Artifacts", Artifacts)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class Audit(betterproto2.Message):
    context: "TaskContext | None" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, optional=True
    )

    command: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        2, betterproto2.TYPE_STRING
    )

    request: "_implantpb__.Spite | None" = betterproto2.field(
        3, betterproto2.TYPE_MESSAGE, optional=True
    )

    created: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        4, betterproto2.TYPE_STRING
    )

    finished: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        5, betterproto2.TYPE_STRING
    )

    lasted: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        6, betterproto2.TYPE_STRING
    )


default_message_pool.register_message("clientpb", "Audit", Audit)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class Audits(betterproto2.Message):
    audit: "list[Audit]" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, repeated=True
    )


default_message_pool.register_message("clientpb", "Audits", Audits)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class Basic(betterproto2.Message):
    version: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        1, betterproto2.TYPE_STRING
    )

    commit: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        4, betterproto2.TYPE_STRING
    )

    dirty: "bool" = betterproto2.field(5, betterproto2.TYPE_BOOL)

    compiled_at: "typing.Annotated[int, pydantic.Field(ge=-2**63, le=2**63 - 1)]" = (
        betterproto2.field(6, betterproto2.TYPE_INT64)
    )

    os: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        7, betterproto2.TYPE_STRING
    )

    arch: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        8, betterproto2.TYPE_STRING
    )


default_message_pool.register_message("clientpb", "Basic", Basic)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class BasicUpdateSession(betterproto2.Message):
    session_id: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        1, betterproto2.TYPE_STRING
    )

    op: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        2, betterproto2.TYPE_STRING
    )

    arg: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        3, betterproto2.TYPE_STRING
    )


default_message_pool.register_message(
    "clientpb", "BasicUpdateSession", BasicUpdateSession
)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class Bin(betterproto2.Message):
    bin: "bytes" = betterproto2.field(1, betterproto2.TYPE_BYTES)


default_message_pool.register_message("clientpb", "Bin", Bin)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class BindPipeline(betterproto2.Message):
    name: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        1, betterproto2.TYPE_STRING
    )

    listener_id: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        2, betterproto2.TYPE_STRING
    )


default_message_pool.register_message("clientpb", "BindPipeline", BindPipeline)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class BuildConfig(betterproto2.Message):
    """


    Oneofs:
        - source_config:
    """

    build_name: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        1, betterproto2.TYPE_STRING
    )

    build_type: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        2, betterproto2.TYPE_STRING
    )

    target: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        3, betterproto2.TYPE_STRING
    )

    source: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        4, betterproto2.TYPE_STRING
    )

    profile_name: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        5, betterproto2.TYPE_STRING
    )

    artifact_id: "typing.Annotated[int, pydantic.Field(ge=0, le=2**32 - 1)]" = (
        betterproto2.field(6, betterproto2.TYPE_UINT32)
    )

    malefic_config: "bytes" = betterproto2.field(7, betterproto2.TYPE_BYTES)

    prelude_config: "bytes" = betterproto2.field(8, betterproto2.TYPE_BYTES)

    resources: "BuildResources | None" = betterproto2.field(
        9, betterproto2.TYPE_MESSAGE, optional=True
    )

    docker: "DockerBuildConfig | None" = betterproto2.field(
        10, betterproto2.TYPE_MESSAGE, optional=True, group="source_config"
    )

    github_action: "GithubActionBuildConfig | None" = betterproto2.field(
        11, betterproto2.TYPE_MESSAGE, optional=True, group="source_config"
    )

    saas: "SaasBuildConfig | None" = betterproto2.field(
        12, betterproto2.TYPE_MESSAGE, optional=True, group="source_config"
    )

    @model_validator(mode="after")
    def check_oneof(cls, values):
        return cls._validate_field_groups(values)


default_message_pool.register_message("clientpb", "BuildConfig", BuildConfig)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class BuildResources(betterproto2.Message):
    entries: "list[ResourceEntry]" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, repeated=True
    )


default_message_pool.register_message("clientpb", "BuildResources", BuildResources)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class Cert(betterproto2.Message):
    cert: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        1, betterproto2.TYPE_STRING
    )

    key: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        2, betterproto2.TYPE_STRING
    )

    name: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        3, betterproto2.TYPE_STRING
    )

    type: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        4, betterproto2.TYPE_STRING
    )


default_message_pool.register_message("clientpb", "Cert", Cert)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class CertificateSubject(betterproto2.Message):
    cn: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        1, betterproto2.TYPE_STRING
    )
    """
    Common Name
    """

    o: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        2, betterproto2.TYPE_STRING
    )
    """
    Organization
    """

    c: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        3, betterproto2.TYPE_STRING
    )
    """
    Country
    """

    l: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        4, betterproto2.TYPE_STRING
    )
    """
    Locality/City
    """

    ou: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        5, betterproto2.TYPE_STRING
    )
    """
    Organizational Unit
    """

    st: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        6, betterproto2.TYPE_STRING
    )
    """
    State/Province
    """

    validity: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        7, betterproto2.TYPE_STRING
    )
    """
    Validity period in days
    """


default_message_pool.register_message(
    "clientpb", "CertificateSubject", CertificateSubject
)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class Certs(betterproto2.Message):
    certs: "list[Tls]" = betterproto2.field(1, betterproto2.TYPE_MESSAGE, repeated=True)


default_message_pool.register_message("clientpb", "Certs", Certs)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class Client(betterproto2.Message):
    id: "typing.Annotated[int, pydantic.Field(ge=0, le=2**32 - 1)]" = (
        betterproto2.field(1, betterproto2.TYPE_UINT32)
    )

    name: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        2, betterproto2.TYPE_STRING
    )

    online: "bool" = betterproto2.field(3, betterproto2.TYPE_BOOL)

    type: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        4, betterproto2.TYPE_STRING
    )


default_message_pool.register_message("clientpb", "Client", Client)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class Clients(betterproto2.Message):
    clients: "list[Client]" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, repeated=True
    )


default_message_pool.register_message("clientpb", "Clients", Clients)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class Context(betterproto2.Message):
    id: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        1, betterproto2.TYPE_STRING
    )

    session: "Session | None" = betterproto2.field(
        2, betterproto2.TYPE_MESSAGE, optional=True
    )

    task: "Task | None" = betterproto2.field(
        3, betterproto2.TYPE_MESSAGE, optional=True
    )

    pipeline: "Pipeline | None" = betterproto2.field(
        4, betterproto2.TYPE_MESSAGE, optional=True
    )

    listener: "Listener | None" = betterproto2.field(
        5, betterproto2.TYPE_MESSAGE, optional=True
    )

    type: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        6, betterproto2.TYPE_STRING
    )

    value: "bytes" = betterproto2.field(7, betterproto2.TYPE_BYTES)

    content: "bytes" = betterproto2.field(8, betterproto2.TYPE_BYTES)

    nonce: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        9, betterproto2.TYPE_STRING
    )


default_message_pool.register_message("clientpb", "Context", Context)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class Contexts(betterproto2.Message):
    contexts: "list[Context]" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, repeated=True
    )


default_message_pool.register_message("clientpb", "Contexts", Contexts)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class CtrlPipeline(betterproto2.Message):
    listener_id: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        1, betterproto2.TYPE_STRING
    )

    name: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        2, betterproto2.TYPE_STRING
    )

    pipeline: "Pipeline | None" = betterproto2.field(
        5, betterproto2.TYPE_MESSAGE, optional=True
    )

    cert_name: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        6, betterproto2.TYPE_STRING
    )


default_message_pool.register_message("clientpb", "CtrlPipeline", CtrlPipeline)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class Dll2Shellcode(betterproto2.Message):
    bin: "bytes" = betterproto2.field(1, betterproto2.TYPE_BYTES)

    type: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        2, betterproto2.TYPE_STRING
    )
    """
    donut
    """

    arch: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        3, betterproto2.TYPE_STRING
    )
    """
    x86 or x64
    """

    params: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        4, betterproto2.TYPE_STRING
    )

    entrypoint: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        5, betterproto2.TYPE_STRING
    )


default_message_pool.register_message("clientpb", "DLL2Shellcode", Dll2Shellcode)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class DockerBuildConfig(betterproto2.Message):
    remote_host: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        1, betterproto2.TYPE_STRING
    )

    volumes: "list[typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]]" = betterproto2.field(
        2, betterproto2.TYPE_STRING, repeated=True
    )


default_message_pool.register_message(
    "clientpb", "DockerBuildConfig", DockerBuildConfig
)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class Empty(betterproto2.Message):
    pass


default_message_pool.register_message("clientpb", "Empty", Empty)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class Encryption(betterproto2.Message):
    type: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        2, betterproto2.TYPE_STRING
    )

    key: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        3, betterproto2.TYPE_STRING
    )


default_message_pool.register_message("clientpb", "Encryption", Encryption)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class Event(betterproto2.Message):
    type: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        1, betterproto2.TYPE_STRING
    )

    op: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        2, betterproto2.TYPE_STRING
    )

    formatted: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        4, betterproto2.TYPE_STRING
    )

    message: "bytes" = betterproto2.field(5, betterproto2.TYPE_BYTES)

    err: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        6, betterproto2.TYPE_STRING
    )
    """
    Can't trigger normal gRPC error
    """

    callee: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        7, betterproto2.TYPE_STRING
    )

    session: "Session | None" = betterproto2.field(
        10, betterproto2.TYPE_MESSAGE, optional=True
    )

    job: "Job | None" = betterproto2.field(11, betterproto2.TYPE_MESSAGE, optional=True)

    client: "Client | None" = betterproto2.field(
        12, betterproto2.TYPE_MESSAGE, optional=True
    )

    task: "Task | None" = betterproto2.field(
        13, betterproto2.TYPE_MESSAGE, optional=True
    )

    spite: "_implantpb__.Spite | None" = betterproto2.field(
        14, betterproto2.TYPE_MESSAGE, optional=True
    )


default_message_pool.register_message("clientpb", "Event", Event)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class Events(betterproto2.Message):
    events: "list[Event]" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, repeated=True
    )


default_message_pool.register_message("clientpb", "Events", Events)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class Exe2Shellcode(betterproto2.Message):
    bin: "bytes" = betterproto2.field(1, betterproto2.TYPE_BYTES)

    type: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        2, betterproto2.TYPE_STRING
    )
    """
    donut
    """

    arch: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        3, betterproto2.TYPE_STRING
    )
    """
    x86 or x64
    """

    params: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        4, betterproto2.TYPE_STRING
    )


default_message_pool.register_message("clientpb", "EXE2Shellcode", Exe2Shellcode)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class File(betterproto2.Message):
    task_id: "typing.Annotated[int, pydantic.Field(ge=0, le=2**32 - 1)]" = (
        betterproto2.field(1, betterproto2.TYPE_UINT32)
    )

    name: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        2, betterproto2.TYPE_STRING
    )

    local: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        3, betterproto2.TYPE_STRING
    )
    """
    client
    """

    checksum: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        4, betterproto2.TYPE_STRING
    )
    """
    server
    """

    remote: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        5, betterproto2.TYPE_STRING
    )
    """
    implant
    """

    op: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        6, betterproto2.TYPE_STRING
    )

    session_id: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        7, betterproto2.TYPE_STRING
    )


default_message_pool.register_message("clientpb", "File", File)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class Files(betterproto2.Message):
    files: "list[File]" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, repeated=True
    )


default_message_pool.register_message("clientpb", "Files", Files)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class GithubActionBuildConfig(betterproto2.Message):
    owner: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        1, betterproto2.TYPE_STRING
    )

    repo: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        2, betterproto2.TYPE_STRING
    )

    token: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        3, betterproto2.TYPE_STRING
    )

    workflow_id: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        4, betterproto2.TYPE_STRING
    )

    inputs: "dict[str, str]" = betterproto2.field(
        5,
        betterproto2.TYPE_MAP,
        map_meta=betterproto2.map_meta(
            betterproto2.TYPE_STRING, betterproto2.TYPE_STRING
        ),
    )

    is_remove: "bool" = betterproto2.field(6, betterproto2.TYPE_BOOL)


default_message_pool.register_message(
    "clientpb", "GithubActionBuildConfig", GithubActionBuildConfig
)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class GithubWorkflow(betterproto2.Message):
    id: "typing.Annotated[int, pydantic.Field(ge=-2**63, le=2**63 - 1)]" = (
        betterproto2.field(1, betterproto2.TYPE_INT64)
    )
    """
    Workflow ID
    """

    node_id: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        2, betterproto2.TYPE_STRING
    )
    """
    Workflow node ID
    """

    name: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        3, betterproto2.TYPE_STRING
    )
    """
    Workflow name
    """

    path: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        4, betterproto2.TYPE_STRING
    )
    """
    Workflow file path
    """

    status: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        5, betterproto2.TYPE_STRING
    )
    """
    Workflow state
    """

    created_at: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        6, betterproto2.TYPE_STRING
    )
    """
    Workflow creation time
    """

    updated_at: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        7, betterproto2.TYPE_STRING
    )
    """
    Workflow last updated time
    """

    url: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        8, betterproto2.TYPE_STRING
    )
    """
    API URL for the workflow
    """

    html_url: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        9, betterproto2.TYPE_STRING
    )
    """
    HTML URL for the workflow
    """

    badge_url: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        10, betterproto2.TYPE_STRING
    )
    """
    Badge URL for the workflow
    """


default_message_pool.register_message("clientpb", "GithubWorkflow", GithubWorkflow)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class GithubWorkflowConfig(betterproto2.Message):
    owner: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        1, betterproto2.TYPE_STRING
    )
    """
    Repository owner
    """

    repo: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        2, betterproto2.TYPE_STRING
    )
    """
    Repository name
    """

    workflow_id: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        3, betterproto2.TYPE_STRING
    )
    """
    Workflow file name or ID
    """

    token: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        4, betterproto2.TYPE_STRING
    )
    """
    GitHub token
    """

    is_remove: "bool" = betterproto2.field(5, betterproto2.TYPE_BOOL)


default_message_pool.register_message(
    "clientpb", "GithubWorkflowConfig", GithubWorkflowConfig
)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class GithubWorkflows(betterproto2.Message):
    workflows: "list[GithubWorkflow]" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, repeated=True
    )
    """
    List of workflows
    """


default_message_pool.register_message("clientpb", "GithubWorkflows", GithubWorkflows)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class HttpPipeline(betterproto2.Message):
    name: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        1, betterproto2.TYPE_STRING
    )

    listener_id: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        2, betterproto2.TYPE_STRING
    )

    port: "typing.Annotated[int, pydantic.Field(ge=0, le=2**32 - 1)]" = (
        betterproto2.field(3, betterproto2.TYPE_UINT32)
    )

    host: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        4, betterproto2.TYPE_STRING
    )

    params: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        5, betterproto2.TYPE_STRING
    )
    """
    JSON serialized additional parameters
    """

    proxy: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        6, betterproto2.TYPE_STRING
    )


default_message_pool.register_message("clientpb", "HTTPPipeline", HttpPipeline)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class Int(betterproto2.Message):
    limit: "typing.Annotated[int, pydantic.Field(ge=-2**31, le=2**31 - 1)]" = (
        betterproto2.field(1, betterproto2.TYPE_INT32)
    )


default_message_pool.register_message("clientpb", "Int", Int)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class Job(betterproto2.Message):
    """


    Oneofs:
        - body:
    """

    id: "typing.Annotated[int, pydantic.Field(ge=0, le=2**32 - 1)]" = (
        betterproto2.field(1, betterproto2.TYPE_UINT32)
    )

    name: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        2, betterproto2.TYPE_STRING
    )

    pipeline: "Pipeline | None" = betterproto2.field(
        3, betterproto2.TYPE_MESSAGE, optional=True
    )

    contents: "dict[str, WebContent]" = betterproto2.field(
        4,
        betterproto2.TYPE_MAP,
        map_meta=betterproto2.map_meta(
            betterproto2.TYPE_STRING, betterproto2.TYPE_MESSAGE
        ),
    )

    rem_agent: "RemAgent | None" = betterproto2.field(
        10, betterproto2.TYPE_MESSAGE, optional=True, group="body"
    )

    rem_log: "RemLog | None" = betterproto2.field(
        11, betterproto2.TYPE_MESSAGE, optional=True, group="body"
    )

    @model_validator(mode="after")
    def check_oneof(cls, values):
        return cls._validate_field_groups(values)


default_message_pool.register_message("clientpb", "Job", Job)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class JobCtrl(betterproto2.Message):
    id: "typing.Annotated[int, pydantic.Field(ge=0, le=2**32 - 1)]" = (
        betterproto2.field(1, betterproto2.TYPE_UINT32)
    )

    ctrl: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        2, betterproto2.TYPE_STRING
    )

    job: "Job | None" = betterproto2.field(3, betterproto2.TYPE_MESSAGE, optional=True)

    content: "WebContent | None" = betterproto2.field(
        4, betterproto2.TYPE_MESSAGE, optional=True
    )

    session: "Session | None" = betterproto2.field(
        5, betterproto2.TYPE_MESSAGE, optional=True
    )


default_message_pool.register_message("clientpb", "JobCtrl", JobCtrl)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class Jobs(betterproto2.Message):
    job: "list[Job]" = betterproto2.field(1, betterproto2.TYPE_MESSAGE, repeated=True)


default_message_pool.register_message("clientpb", "Jobs", Jobs)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class JobStatus(betterproto2.Message):
    listener_id: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        1, betterproto2.TYPE_STRING
    )

    ctrl: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        2, betterproto2.TYPE_STRING
    )

    status: "typing.Annotated[int, pydantic.Field(ge=-2**31, le=2**31 - 1)]" = (
        betterproto2.field(3, betterproto2.TYPE_INT32)
    )

    error: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        4, betterproto2.TYPE_STRING
    )

    job: "Job | None" = betterproto2.field(5, betterproto2.TYPE_MESSAGE, optional=True)

    ctrl_id: "typing.Annotated[int, pydantic.Field(ge=0, le=2**32 - 1)]" = (
        betterproto2.field(6, betterproto2.TYPE_UINT32)
    )

    content: "WebContent | None" = betterproto2.field(
        7, betterproto2.TYPE_MESSAGE, optional=True
    )


default_message_pool.register_message("clientpb", "JobStatus", JobStatus)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class KeyPair(betterproto2.Message):
    public_key: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        1, betterproto2.TYPE_STRING
    )
    """
    公钥
    """

    private_key: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        2, betterproto2.TYPE_STRING
    )
    """
    私钥
    """


default_message_pool.register_message("clientpb", "KeyPair", KeyPair)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class LicenseInfo(betterproto2.Message):
    user_name: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        1, betterproto2.TYPE_STRING
    )

    type: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        2, betterproto2.TYPE_STRING
    )

    expire_at: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        3, betterproto2.TYPE_STRING
    )

    build_count: "typing.Annotated[int, pydantic.Field(ge=-2**63, le=2**63 - 1)]" = (
        betterproto2.field(4, betterproto2.TYPE_INT64)
    )

    max_builds: "typing.Annotated[int, pydantic.Field(ge=-2**63, le=2**63 - 1)]" = (
        betterproto2.field(5, betterproto2.TYPE_INT64)
    )


default_message_pool.register_message("clientpb", "LicenseInfo", LicenseInfo)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class Listener(betterproto2.Message):
    id: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        1, betterproto2.TYPE_STRING
    )

    ip: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        2, betterproto2.TYPE_STRING
    )

    active: "bool" = betterproto2.field(3, betterproto2.TYPE_BOOL)

    pipelines: "Pipelines | None" = betterproto2.field(
        4, betterproto2.TYPE_MESSAGE, optional=True
    )


default_message_pool.register_message("clientpb", "Listener", Listener)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class Listeners(betterproto2.Message):
    listeners: "list[Listener]" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, repeated=True
    )


default_message_pool.register_message("clientpb", "Listeners", Listeners)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class LoginReq(betterproto2.Message):
    host: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        1, betterproto2.TYPE_STRING
    )

    port: "typing.Annotated[int, pydantic.Field(ge=0, le=2**32 - 1)]" = (
        betterproto2.field(2, betterproto2.TYPE_UINT32)
    )

    name: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        3, betterproto2.TYPE_STRING
    )


default_message_pool.register_message("clientpb", "LoginReq", LoginReq)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class Notify(betterproto2.Message):
    telegram_enable: "bool" = betterproto2.field(1, betterproto2.TYPE_BOOL)

    telegram_api_key: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        2, betterproto2.TYPE_STRING
    )

    telegram_chat_id: "typing.Annotated[int, pydantic.Field(ge=-2**63, le=2**63 - 1)]" = betterproto2.field(
        3, betterproto2.TYPE_INT64
    )

    dingtalk_enable: "bool" = betterproto2.field(4, betterproto2.TYPE_BOOL)

    dingtalk_secret: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        5, betterproto2.TYPE_STRING
    )

    dingtalk_token: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        6, betterproto2.TYPE_STRING
    )

    lark_enable: "bool" = betterproto2.field(7, betterproto2.TYPE_BOOL)

    lark_webhook_url: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        8, betterproto2.TYPE_STRING
    )

    serverchan_enable: "bool" = betterproto2.field(9, betterproto2.TYPE_BOOL)

    serverchan_url: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        10, betterproto2.TYPE_STRING
    )

    pushplus_enable: "bool" = betterproto2.field(11, betterproto2.TYPE_BOOL)

    pushplus_token: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        12, betterproto2.TYPE_STRING
    )

    pushplus_topic: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        13, betterproto2.TYPE_STRING
    )

    pushplus_channel: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        14, betterproto2.TYPE_STRING
    )


default_message_pool.register_message("clientpb", "Notify", Notify)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class On(betterproto2.Message):
    id: "typing.Annotated[int, pydantic.Field(ge=-2**31, le=2**31 - 1)]" = (
        betterproto2.field(1, betterproto2.TYPE_INT32)
    )

    event_type: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        2, betterproto2.TYPE_STRING
    )

    event_op: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        3, betterproto2.TYPE_STRING
    )

    message_name: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        4, betterproto2.TYPE_STRING
    )

    session_id: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        5, betterproto2.TYPE_STRING
    )

    task_id: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        6, betterproto2.TYPE_STRING
    )

    pipeline_id: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        7, betterproto2.TYPE_STRING
    )

    listener_id: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        8, betterproto2.TYPE_STRING
    )


default_message_pool.register_message("clientpb", "On", On)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class Pipeline(betterproto2.Message):
    """


    Oneofs:
        - body:
    """

    name: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        1, betterproto2.TYPE_STRING
    )

    enable: "bool" = betterproto2.field(2, betterproto2.TYPE_BOOL)

    type: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        3, betterproto2.TYPE_STRING
    )

    listener_id: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        4, betterproto2.TYPE_STRING
    )

    parser: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        5, betterproto2.TYPE_STRING
    )

    tls: "Tls | None" = betterproto2.field(8, betterproto2.TYPE_MESSAGE, optional=True)

    encryption: "list[Encryption]" = betterproto2.field(
        9, betterproto2.TYPE_MESSAGE, repeated=True
    )

    ip: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        10, betterproto2.TYPE_STRING
    )

    cert_name: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        11, betterproto2.TYPE_STRING
    )

    secure: "Secure | None" = betterproto2.field(
        12, betterproto2.TYPE_MESSAGE, optional=True
    )
    """
    Age 安全配置
    """

    tcp: "TcpPipeline | None" = betterproto2.field(
        20, betterproto2.TYPE_MESSAGE, optional=True, group="body"
    )

    bind: "BindPipeline | None" = betterproto2.field(
        21, betterproto2.TYPE_MESSAGE, optional=True, group="body"
    )

    rem: "Rem | None" = betterproto2.field(
        22, betterproto2.TYPE_MESSAGE, optional=True, group="body"
    )

    web: "Website | None" = betterproto2.field(
        23, betterproto2.TYPE_MESSAGE, optional=True, group="body"
    )

    http: "HttpPipeline | None" = betterproto2.field(
        24, betterproto2.TYPE_MESSAGE, optional=True, group="body"
    )

    @model_validator(mode="after")
    def check_oneof(cls, values):
        return cls._validate_field_groups(values)


default_message_pool.register_message("clientpb", "Pipeline", Pipeline)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class Pipelines(betterproto2.Message):
    pipelines: "list[Pipeline]" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, repeated=True
    )


default_message_pool.register_message("clientpb", "Pipelines", Pipelines)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class Plugin(betterproto2.Message):
    name: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        1, betterproto2.TYPE_STRING
    )

    content: "bytes" = betterproto2.field(2, betterproto2.TYPE_BYTES)


default_message_pool.register_message("clientpb", "Plugin", Plugin)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class Plugins(betterproto2.Message):
    plugins: "list[Plugin]" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, repeated=True
    )


default_message_pool.register_message("clientpb", "Plugins", Plugins)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class Polling(betterproto2.Message):
    id: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        1, betterproto2.TYPE_STRING
    )

    session_id: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        2, betterproto2.TYPE_STRING
    )

    interval: "typing.Annotated[int, pydantic.Field(ge=0, le=2**64 - 1)]" = (
        betterproto2.field(3, betterproto2.TYPE_UINT64)
    )

    tasks: "list[typing.Annotated[int, pydantic.Field(ge=0, le=2**32 - 1)]]" = (
        betterproto2.field(4, betterproto2.TYPE_UINT32, repeated=True)
    )

    force: "bool" = betterproto2.field(5, betterproto2.TYPE_BOOL)


default_message_pool.register_message("clientpb", "Polling", Polling)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class Profile(betterproto2.Message):
    name: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        1, betterproto2.TYPE_STRING
    )

    target: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        2, betterproto2.TYPE_STRING
    )

    proxy: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        4, betterproto2.TYPE_STRING
    )

    params: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        8, betterproto2.TYPE_STRING
    )

    pipeline_id: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        9, betterproto2.TYPE_STRING
    )

    content: "bytes" = betterproto2.field(11, betterproto2.TYPE_BYTES)

    created_at: "typing.Annotated[int, pydantic.Field(ge=-2**63, le=2**63 - 1)]" = (
        betterproto2.field(12, betterproto2.TYPE_INT64)
    )


default_message_pool.register_message("clientpb", "Profile", Profile)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class Profiles(betterproto2.Message):
    profiles: "list[Profile]" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, repeated=True
    )


default_message_pool.register_message("clientpb", "Profiles", Profiles)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class RegisterListener(betterproto2.Message):
    id: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        1, betterproto2.TYPE_STRING
    )

    host: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        2, betterproto2.TYPE_STRING
    )

    name: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        3, betterproto2.TYPE_STRING
    )

    addr: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        4, betterproto2.TYPE_STRING
    )

    pipelines: "Pipelines | None" = betterproto2.field(
        5, betterproto2.TYPE_MESSAGE, optional=True
    )


default_message_pool.register_message("clientpb", "RegisterListener", RegisterListener)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class RegisterSession(betterproto2.Message):
    session_id: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        1, betterproto2.TYPE_STRING
    )

    pipeline_id: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        2, betterproto2.TYPE_STRING
    )

    listener_id: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        3, betterproto2.TYPE_STRING
    )

    target: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        4, betterproto2.TYPE_STRING
    )

    raw_id: "typing.Annotated[int, pydantic.Field(ge=0, le=2**32 - 1)]" = (
        betterproto2.field(5, betterproto2.TYPE_UINT32)
    )

    type: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        6, betterproto2.TYPE_STRING
    )

    register_data: "_modulepb__.Register | None" = betterproto2.field(
        7, betterproto2.TYPE_MESSAGE, optional=True
    )


default_message_pool.register_message("clientpb", "RegisterSession", RegisterSession)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class Rem(betterproto2.Message):
    name: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        1, betterproto2.TYPE_STRING
    )

    listener_id: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        2, betterproto2.TYPE_STRING
    )

    port: "typing.Annotated[int, pydantic.Field(ge=0, le=2**32 - 1)]" = (
        betterproto2.field(3, betterproto2.TYPE_UINT32)
    )

    host: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        4, betterproto2.TYPE_STRING
    )

    console: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        5, betterproto2.TYPE_STRING
    )

    link: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        6, betterproto2.TYPE_STRING
    )

    subscribe: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        7, betterproto2.TYPE_STRING
    )

    agents: "dict[str, RemAgent]" = betterproto2.field(
        10,
        betterproto2.TYPE_MAP,
        map_meta=betterproto2.map_meta(
            betterproto2.TYPE_STRING, betterproto2.TYPE_MESSAGE
        ),
    )


default_message_pool.register_message("clientpb", "REM", Rem)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class RemAgent(betterproto2.Message):
    pipeline_id: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        1, betterproto2.TYPE_STRING
    )

    id: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        2, betterproto2.TYPE_STRING
    )

    mod: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        3, betterproto2.TYPE_STRING
    )

    local: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        4, betterproto2.TYPE_STRING
    )

    remote: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        5, betterproto2.TYPE_STRING
    )

    enable: "bool" = betterproto2.field(6, betterproto2.TYPE_BOOL)

    args: "list[typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]]" = betterproto2.field(
        7, betterproto2.TYPE_STRING, repeated=True
    )


default_message_pool.register_message("clientpb", "REMAgent", RemAgent)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class RemAgents(betterproto2.Message):
    agents: "list[RemAgent]" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, repeated=True
    )


default_message_pool.register_message("clientpb", "REMAgents", RemAgents)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class RemLog(betterproto2.Message):
    pipeline_id: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        1, betterproto2.TYPE_STRING
    )

    agent_id: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        2, betterproto2.TYPE_STRING
    )

    log: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        3, betterproto2.TYPE_STRING
    )


default_message_pool.register_message("clientpb", "RemLog", RemLog)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class ResourceEntry(betterproto2.Message):
    filename: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        1, betterproto2.TYPE_STRING
    )

    content: "bytes" = betterproto2.field(2, betterproto2.TYPE_BYTES)


default_message_pool.register_message("clientpb", "ResourceEntry", ResourceEntry)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class SaasBuildConfig(betterproto2.Message):
    url: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        1, betterproto2.TYPE_STRING
    )

    token: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        2, betterproto2.TYPE_STRING
    )

    headers: "dict[str, str]" = betterproto2.field(
        3,
        betterproto2.TYPE_MAP,
        map_meta=betterproto2.map_meta(
            betterproto2.TYPE_STRING, betterproto2.TYPE_STRING
        ),
    )


default_message_pool.register_message("clientpb", "SaasBuildConfig", SaasBuildConfig)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class Secure(betterproto2.Message):
    enable: "bool" = betterproto2.field(1, betterproto2.TYPE_BOOL)
    """
    是否启用安全模式
    """

    server_keypair: "KeyPair | None" = betterproto2.field(
        2, betterproto2.TYPE_MESSAGE, optional=True
    )
    """
    server密钥对
    """

    implant_keypair: "KeyPair | None" = betterproto2.field(
        3, betterproto2.TYPE_MESSAGE, optional=True
    )
    """
    implant密钥对
    """


default_message_pool.register_message("clientpb", "Secure", Secure)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class Session(betterproto2.Message):
    session_id: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        1, betterproto2.TYPE_STRING
    )

    raw_id: "typing.Annotated[int, pydantic.Field(ge=0, le=2**32 - 1)]" = (
        betterproto2.field(2, betterproto2.TYPE_UINT32)
    )

    name: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        3, betterproto2.TYPE_STRING
    )

    type: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        4, betterproto2.TYPE_STRING
    )

    note: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        5, betterproto2.TYPE_STRING
    )

    pipeline_id: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        6, betterproto2.TYPE_STRING
    )

    listener_id: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        7, betterproto2.TYPE_STRING
    )

    group_name: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        8, betterproto2.TYPE_STRING
    )

    target: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        9, betterproto2.TYPE_STRING
    )

    is_alive: "bool" = betterproto2.field(10, betterproto2.TYPE_BOOL)

    is_privilege: "bool" = betterproto2.field(11, betterproto2.TYPE_BOOL)

    is_initialized: "bool" = betterproto2.field(12, betterproto2.TYPE_BOOL)

    last_checkin: "typing.Annotated[int, pydantic.Field(ge=-2**63, le=2**63 - 1)]" = (
        betterproto2.field(13, betterproto2.TYPE_INT64)
    )

    tasks: "Tasks | None" = betterproto2.field(
        15, betterproto2.TYPE_MESSAGE, optional=True
    )

    filepath: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        16, betterproto2.TYPE_STRING
    )

    locate: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        17, betterproto2.TYPE_STRING
    )

    workdir: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        18, betterproto2.TYPE_STRING
    )

    proxy: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        19, betterproto2.TYPE_STRING
    )

    os: "_modulepb__.Os | None" = betterproto2.field(
        20, betterproto2.TYPE_MESSAGE, optional=True
    )

    process: "_modulepb__.Process | None" = betterproto2.field(
        21, betterproto2.TYPE_MESSAGE, optional=True
    )

    timer: "_modulepb__.Timer | None" = betterproto2.field(
        22, betterproto2.TYPE_MESSAGE, optional=True
    )

    created_at: "typing.Annotated[int, pydantic.Field(ge=-2**63, le=2**63 - 1)]" = (
        betterproto2.field(23, betterproto2.TYPE_INT64)
    )

    modules: "list[typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]]" = betterproto2.field(
        30, betterproto2.TYPE_STRING, repeated=True
    )

    addons: "list[_modulepb__.Addon]" = betterproto2.field(
        31, betterproto2.TYPE_MESSAGE, repeated=True
    )

    key_pair: "KeyPair | None" = betterproto2.field(
        32, betterproto2.TYPE_MESSAGE, optional=True
    )
    """
    Age 密钥对
    """

    argue: "dict[str, str]" = betterproto2.field(
        40,
        betterproto2.TYPE_MAP,
        map_meta=betterproto2.map_meta(
            betterproto2.TYPE_STRING, betterproto2.TYPE_STRING
        ),
    )

    data: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        41, betterproto2.TYPE_STRING
    )

    loot: "dict[str, str]" = betterproto2.field(
        42,
        betterproto2.TYPE_MAP,
        map_meta=betterproto2.map_meta(
            betterproto2.TYPE_STRING, betterproto2.TYPE_STRING
        ),
    )


default_message_pool.register_message("clientpb", "Session", Session)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class SessionRequest(betterproto2.Message):
    session_id: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        1, betterproto2.TYPE_STRING
    )

    all: "bool" = betterproto2.field(2, betterproto2.TYPE_BOOL)


default_message_pool.register_message("clientpb", "SessionRequest", SessionRequest)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class Sessions(betterproto2.Message):
    sessions: "list[Session]" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, repeated=True
    )


default_message_pool.register_message("clientpb", "Sessions", Sessions)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class ShellcodeEncode(betterproto2.Message):
    shellcode: "bytes" = betterproto2.field(1, betterproto2.TYPE_BYTES)

    type: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        2, betterproto2.TYPE_STRING
    )
    """
    sgn
    """

    arch: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        3, betterproto2.TYPE_STRING
    )
    """
    x86 or x64
    """

    iterations: "typing.Annotated[int, pydantic.Field(ge=-2**31, le=2**31 - 1)]" = (
        betterproto2.field(4, betterproto2.TYPE_INT32)
    )


default_message_pool.register_message("clientpb", "ShellcodeEncode", ShellcodeEncode)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class SpiteCache(betterproto2.Message):
    items: "list[SpiteCacheItem]" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, repeated=True
    )


default_message_pool.register_message("clientpb", "SpiteCache", SpiteCache)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class SpiteCacheItem(betterproto2.Message):
    index: "typing.Annotated[int, pydantic.Field(ge=-2**31, le=2**31 - 1)]" = (
        betterproto2.field(1, betterproto2.TYPE_INT32)
    )

    id: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        2, betterproto2.TYPE_STRING
    )

    spite: "_implantpb__.Spite | None" = betterproto2.field(
        3, betterproto2.TYPE_MESSAGE, optional=True
    )

    expiration: "typing.Annotated[int, pydantic.Field(ge=-2**63, le=2**63 - 1)]" = (
        betterproto2.field(4, betterproto2.TYPE_INT64)
    )


default_message_pool.register_message("clientpb", "SpiteCacheItem", SpiteCacheItem)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class SpiteRequest(betterproto2.Message):
    listener_id: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        1, betterproto2.TYPE_STRING
    )

    session: "Session | None" = betterproto2.field(
        2, betterproto2.TYPE_MESSAGE, optional=True
    )

    task: "Task | None" = betterproto2.field(
        3, betterproto2.TYPE_MESSAGE, optional=True
    )

    spite: "_implantpb__.Spite | None" = betterproto2.field(
        4, betterproto2.TYPE_MESSAGE, optional=True
    )


default_message_pool.register_message("clientpb", "SpiteRequest", SpiteRequest)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class SpiteResponse(betterproto2.Message):
    listener_id: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        1, betterproto2.TYPE_STRING
    )

    session_id: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        2, betterproto2.TYPE_STRING
    )

    task_id: "typing.Annotated[int, pydantic.Field(ge=0, le=2**32 - 1)]" = (
        betterproto2.field(3, betterproto2.TYPE_UINT32)
    )

    spite: "_implantpb__.Spite | None" = betterproto2.field(
        4, betterproto2.TYPE_MESSAGE, optional=True
    )


default_message_pool.register_message("clientpb", "SpiteResponse", SpiteResponse)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class Sync(betterproto2.Message):
    context_id: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        1, betterproto2.TYPE_STRING
    )

    task_id: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        2, betterproto2.TYPE_STRING
    )


default_message_pool.register_message("clientpb", "Sync", Sync)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class SyncResp(betterproto2.Message):
    name: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        1, betterproto2.TYPE_STRING
    )

    content: "bytes" = betterproto2.field(2, betterproto2.TYPE_BYTES)


default_message_pool.register_message("clientpb", "SyncResp", SyncResp)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class Task(betterproto2.Message):
    task_id: "typing.Annotated[int, pydantic.Field(ge=0, le=2**32 - 1)]" = (
        betterproto2.field(1, betterproto2.TYPE_UINT32)
    )

    session_id: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        2, betterproto2.TYPE_STRING
    )

    type: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        3, betterproto2.TYPE_STRING
    )

    status: "typing.Annotated[int, pydantic.Field(ge=-2**31, le=2**31 - 1)]" = (
        betterproto2.field(4, betterproto2.TYPE_INT32)
    )

    cur: "typing.Annotated[int, pydantic.Field(ge=-2**31, le=2**31 - 1)]" = (
        betterproto2.field(5, betterproto2.TYPE_INT32)
    )

    total: "typing.Annotated[int, pydantic.Field(ge=-2**31, le=2**31 - 1)]" = (
        betterproto2.field(6, betterproto2.TYPE_INT32)
    )

    error: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        7, betterproto2.TYPE_STRING
    )

    need: "typing.Annotated[int, pydantic.Field(ge=-2**31, le=2**31 - 1)]" = (
        betterproto2.field(8, betterproto2.TYPE_INT32)
    )

    description: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        9, betterproto2.TYPE_STRING
    )

    callby: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        10, betterproto2.TYPE_STRING
    )

    finished: "bool" = betterproto2.field(11, betterproto2.TYPE_BOOL)

    timeout: "bool" = betterproto2.field(12, betterproto2.TYPE_BOOL)


default_message_pool.register_message("clientpb", "Task", Task)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class TaskContext(betterproto2.Message):
    task: "Task | None" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, optional=True
    )

    session: "Session | None" = betterproto2.field(
        2, betterproto2.TYPE_MESSAGE, optional=True
    )

    spite: "_implantpb__.Spite | None" = betterproto2.field(
        3, betterproto2.TYPE_MESSAGE, optional=True
    )


default_message_pool.register_message("clientpb", "TaskContext", TaskContext)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class TaskContexts(betterproto2.Message):
    task: "Task | None" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, optional=True
    )

    session: "Session | None" = betterproto2.field(
        2, betterproto2.TYPE_MESSAGE, optional=True
    )

    spites: "list[_implantpb__.Spite]" = betterproto2.field(
        3, betterproto2.TYPE_MESSAGE, repeated=True
    )


default_message_pool.register_message("clientpb", "TaskContexts", TaskContexts)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class TaskDesc(betterproto2.Message):
    task_id: "typing.Annotated[int, pydantic.Field(ge=0, le=2**32 - 1)]" = (
        betterproto2.field(1, betterproto2.TYPE_UINT32)
    )

    cur: "typing.Annotated[int, pydantic.Field(ge=-2**31, le=2**31 - 1)]" = (
        betterproto2.field(2, betterproto2.TYPE_INT32)
    )

    total: "typing.Annotated[int, pydantic.Field(ge=-2**31, le=2**31 - 1)]" = (
        betterproto2.field(3, betterproto2.TYPE_INT32)
    )

    type: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        4, betterproto2.TYPE_STRING
    )

    status: "typing.Annotated[int, pydantic.Field(ge=-2**31, le=2**31 - 1)]" = (
        betterproto2.field(5, betterproto2.TYPE_INT32)
    )

    description: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        6, betterproto2.TYPE_STRING
    )


default_message_pool.register_message("clientpb", "TaskDesc", TaskDesc)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class TaskDescs(betterproto2.Message):
    tasks: "list[TaskDesc]" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, repeated=True
    )


default_message_pool.register_message("clientpb", "TaskDescs", TaskDescs)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class TaskRequest(betterproto2.Message):
    session_id: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        1, betterproto2.TYPE_STRING
    )

    all: "bool" = betterproto2.field(2, betterproto2.TYPE_BOOL)


default_message_pool.register_message("clientpb", "TaskRequest", TaskRequest)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class Tasks(betterproto2.Message):
    tasks: "list[Task]" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, repeated=True
    )


default_message_pool.register_message("clientpb", "Tasks", Tasks)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class TasksContext(betterproto2.Message):
    contexts: "list[TaskContext]" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, repeated=True
    )


default_message_pool.register_message("clientpb", "TasksContext", TasksContext)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class TcpPipeline(betterproto2.Message):
    name: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        1, betterproto2.TYPE_STRING
    )

    listener_id: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        2, betterproto2.TYPE_STRING
    )

    port: "typing.Annotated[int, pydantic.Field(ge=0, le=2**32 - 1)]" = (
        betterproto2.field(3, betterproto2.TYPE_UINT32)
    )

    host: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        4, betterproto2.TYPE_STRING
    )

    proxy: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        5, betterproto2.TYPE_STRING
    )


default_message_pool.register_message("clientpb", "TCPPipeline", TcpPipeline)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class Tls(betterproto2.Message):
    cert: "Cert | None" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, optional=True
    )

    ca: "Cert | None" = betterproto2.field(2, betterproto2.TYPE_MESSAGE, optional=True)

    enable: "bool" = betterproto2.field(4, betterproto2.TYPE_BOOL)

    acme: "bool" = betterproto2.field(5, betterproto2.TYPE_BOOL)

    domain: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        6, betterproto2.TYPE_STRING
    )

    cert_subject: "CertificateSubject | None" = betterproto2.field(
        7, betterproto2.TYPE_MESSAGE, optional=True
    )


default_message_pool.register_message("clientpb", "TLS", Tls)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class WebContent(betterproto2.Message):
    id: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        1, betterproto2.TYPE_STRING
    )

    website_id: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        2, betterproto2.TYPE_STRING
    )

    file: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        3, betterproto2.TYPE_STRING
    )

    path: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        4, betterproto2.TYPE_STRING
    )

    type: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        5, betterproto2.TYPE_STRING
    )

    content_type: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        7, betterproto2.TYPE_STRING
    )

    size: "typing.Annotated[int, pydantic.Field(ge=0, le=2**64 - 1)]" = (
        betterproto2.field(6, betterproto2.TYPE_UINT64)
    )

    url: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        8, betterproto2.TYPE_STRING
    )

    content: "bytes" = betterproto2.field(9, betterproto2.TYPE_BYTES)

    listener_id: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        10, betterproto2.TYPE_STRING
    )


default_message_pool.register_message("clientpb", "WebContent", WebContent)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class WebContents(betterproto2.Message):
    contents: "list[WebContent]" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, repeated=True
    )


default_message_pool.register_message("clientpb", "WebContents", WebContents)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class Website(betterproto2.Message):
    name: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        1, betterproto2.TYPE_STRING
    )

    listener_id: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        2, betterproto2.TYPE_STRING
    )

    port: "typing.Annotated[int, pydantic.Field(ge=0, le=2**32 - 1)]" = (
        betterproto2.field(3, betterproto2.TYPE_UINT32)
    )

    root: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        4, betterproto2.TYPE_STRING
    )

    contents: "dict[str, WebContent]" = betterproto2.field(
        6,
        betterproto2.TYPE_MAP,
        map_meta=betterproto2.map_meta(
            betterproto2.TYPE_STRING, betterproto2.TYPE_MESSAGE
        ),
    )


default_message_pool.register_message("clientpb", "Website", Website)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class Websites(betterproto2.Message):
    websites: "list[Website]" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, repeated=True
    )


default_message_pool.register_message("clientpb", "Websites", Websites)


from .. import implantpb as _implantpb__
from .. import modulepb as _modulepb__
