# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: services/listenerrpc/service.proto
# plugin: python-betterproto2
# This file has been @generated

__all__ = ("ListenerRpcStub", "ListenerRpcSyncStub")

from collections.abc import AsyncIterable, AsyncIterator, Iterable, Iterator
from typing import TYPE_CHECKING

import betterproto2
import grpc

if TYPE_CHECKING:
    from betterproto2.grpc.grpclib_client import MetadataLike
    from grpclib.metadata import Deadline

_COMPILER_VERSION = "0.8.0"
betterproto2.check_compiler_version(_COMPILER_VERSION)


class ListenerRpcSyncStub:
    def __init__(self, channel: grpc.Channel):
        self._channel = channel

    def spite_stream(
        self, messages: "Iterable[_clientpb__.SpiteResponse]"
    ) -> "Iterator[_clientpb__.SpiteRequest]":
        yield from self._channel.stream_stream(
            "/listenerrpc.ListenerRPC/SpiteStream",
            _clientpb__.SpiteResponse.SerializeToString,
            _clientpb__.SpiteRequest.FromString,
        )(iter(messages))

    def job_stream(
        self, messages: "Iterable[_clientpb__.JobStatus]"
    ) -> "Iterator[_clientpb__.JobCtrl]":
        yield from self._channel.stream_stream(
            "/listenerrpc.ListenerRPC/JobStream",
            _clientpb__.JobStatus.SerializeToString,
            _clientpb__.JobCtrl.FromString,
        )(iter(messages))

    def register(self, message: "_clientpb__.RegisterSession") -> "_clientpb__.Empty":
        """
        implant
        """

        return self._channel.unary_unary(
            "/listenerrpc.ListenerRPC/Register",
            _clientpb__.RegisterSession.SerializeToString,
            _clientpb__.Empty.FromString,
        )(message)

    def sys_info(self, message: "_modulepb__.SysInfo") -> "_clientpb__.Empty":
        return self._channel.unary_unary(
            "/listenerrpc.ListenerRPC/SysInfo",
            _modulepb__.SysInfo.SerializeToString,
            _clientpb__.Empty.FromString,
        )(message)

    def checkin(self, message: "_modulepb__.Ping") -> "_clientpb__.Empty":
        return self._channel.unary_unary(
            "/listenerrpc.ListenerRPC/Checkin",
            _modulepb__.Ping.SerializeToString,
            _clientpb__.Empty.FromString,
        )(message)

    def init_bind_session(self, message: "_modulepb__.Request") -> "_clientpb__.Empty":
        return self._channel.unary_unary(
            "/listenerrpc.ListenerRPC/InitBindSession",
            _modulepb__.Request.SerializeToString,
            _clientpb__.Empty.FromString,
        )(message)

    def register_listener(
        self, message: "_clientpb__.RegisterListener"
    ) -> "_clientpb__.Empty":
        """
        pipeline
        """

        return self._channel.unary_unary(
            "/listenerrpc.ListenerRPC/RegisterListener",
            _clientpb__.RegisterListener.SerializeToString,
            _clientpb__.Empty.FromString,
        )(message)

    def register_pipeline(self, message: "_clientpb__.Pipeline") -> "_clientpb__.Empty":
        return self._channel.unary_unary(
            "/listenerrpc.ListenerRPC/RegisterPipeline",
            _clientpb__.Pipeline.SerializeToString,
            _clientpb__.Empty.FromString,
        )(message)

    def start_pipeline(
        self, message: "_clientpb__.CtrlPipeline"
    ) -> "_clientpb__.Empty":
        return self._channel.unary_unary(
            "/listenerrpc.ListenerRPC/StartPipeline",
            _clientpb__.CtrlPipeline.SerializeToString,
            _clientpb__.Empty.FromString,
        )(message)

    def stop_pipeline(self, message: "_clientpb__.CtrlPipeline") -> "_clientpb__.Empty":
        return self._channel.unary_unary(
            "/listenerrpc.ListenerRPC/StopPipeline",
            _clientpb__.CtrlPipeline.SerializeToString,
            _clientpb__.Empty.FromString,
        )(message)

    def delete_pipeline(
        self, message: "_clientpb__.CtrlPipeline"
    ) -> "_clientpb__.Empty":
        return self._channel.unary_unary(
            "/listenerrpc.ListenerRPC/DeletePipeline",
            _clientpb__.CtrlPipeline.SerializeToString,
            _clientpb__.Empty.FromString,
        )(message)

    def list_pipelines(
        self, message: "_clientpb__.Listener"
    ) -> "_clientpb__.Pipelines":
        return self._channel.unary_unary(
            "/listenerrpc.ListenerRPC/ListPipelines",
            _clientpb__.Listener.SerializeToString,
            _clientpb__.Pipelines.FromString,
        )(message)

    def sync_pipeline(self, message: "_clientpb__.Pipeline") -> "_clientpb__.Empty":
        return self._channel.unary_unary(
            "/listenerrpc.ListenerRPC/SyncPipeline",
            _clientpb__.Pipeline.SerializeToString,
            _clientpb__.Empty.FromString,
        )(message)

    def register_website(self, message: "_clientpb__.Pipeline") -> "_clientpb__.Empty":
        """
        website
        """

        return self._channel.unary_unary(
            "/listenerrpc.ListenerRPC/RegisterWebsite",
            _clientpb__.Pipeline.SerializeToString,
            _clientpb__.Empty.FromString,
        )(message)

    def start_website(self, message: "_clientpb__.CtrlPipeline") -> "_clientpb__.Empty":
        return self._channel.unary_unary(
            "/listenerrpc.ListenerRPC/StartWebsite",
            _clientpb__.CtrlPipeline.SerializeToString,
            _clientpb__.Empty.FromString,
        )(message)

    def stop_website(self, message: "_clientpb__.CtrlPipeline") -> "_clientpb__.Empty":
        return self._channel.unary_unary(
            "/listenerrpc.ListenerRPC/StopWebsite",
            _clientpb__.CtrlPipeline.SerializeToString,
            _clientpb__.Empty.FromString,
        )(message)

    def delete_website(
        self, message: "_clientpb__.CtrlPipeline"
    ) -> "_clientpb__.Empty":
        return self._channel.unary_unary(
            "/listenerrpc.ListenerRPC/DeleteWebsite",
            _clientpb__.CtrlPipeline.SerializeToString,
            _clientpb__.Empty.FromString,
        )(message)

    def list_websites(self, message: "_clientpb__.Listener") -> "_clientpb__.Pipelines":
        return self._channel.unary_unary(
            "/listenerrpc.ListenerRPC/ListWebsites",
            _clientpb__.Listener.SerializeToString,
            _clientpb__.Pipelines.FromString,
        )(message)

    def list_web_content(
        self, message: "_clientpb__.Website"
    ) -> "_clientpb__.WebContents":
        return self._channel.unary_unary(
            "/listenerrpc.ListenerRPC/ListWebContent",
            _clientpb__.Website.SerializeToString,
            _clientpb__.WebContents.FromString,
        )(message)

    def add_website_content(
        self, message: "_clientpb__.Website"
    ) -> "_clientpb__.WebContent":
        return self._channel.unary_unary(
            "/listenerrpc.ListenerRPC/AddWebsiteContent",
            _clientpb__.Website.SerializeToString,
            _clientpb__.WebContent.FromString,
        )(message)

    def update_website_content(
        self, message: "_clientpb__.WebContent"
    ) -> "_clientpb__.WebContent":
        return self._channel.unary_unary(
            "/listenerrpc.ListenerRPC/UpdateWebsiteContent",
            _clientpb__.WebContent.SerializeToString,
            _clientpb__.WebContent.FromString,
        )(message)

    def remove_website_content(
        self, message: "_clientpb__.WebContent"
    ) -> "_clientpb__.Empty":
        return self._channel.unary_unary(
            "/listenerrpc.ListenerRPC/RemoveWebsiteContent",
            _clientpb__.WebContent.SerializeToString,
            _clientpb__.Empty.FromString,
        )(message)

    def register_rem(self, message: "_clientpb__.Pipeline") -> "_clientpb__.Empty":
        """
        rem
        """

        return self._channel.unary_unary(
            "/listenerrpc.ListenerRPC/RegisterRem",
            _clientpb__.Pipeline.SerializeToString,
            _clientpb__.Empty.FromString,
        )(message)

    def start_rem(self, message: "_clientpb__.CtrlPipeline") -> "_clientpb__.Empty":
        return self._channel.unary_unary(
            "/listenerrpc.ListenerRPC/StartRem",
            _clientpb__.CtrlPipeline.SerializeToString,
            _clientpb__.Empty.FromString,
        )(message)

    def stop_rem(self, message: "_clientpb__.CtrlPipeline") -> "_clientpb__.Empty":
        return self._channel.unary_unary(
            "/listenerrpc.ListenerRPC/StopRem",
            _clientpb__.CtrlPipeline.SerializeToString,
            _clientpb__.Empty.FromString,
        )(message)

    def delete_rem(self, message: "_clientpb__.CtrlPipeline") -> "_clientpb__.Empty":
        return self._channel.unary_unary(
            "/listenerrpc.ListenerRPC/DeleteRem",
            _clientpb__.CtrlPipeline.SerializeToString,
            _clientpb__.Empty.FromString,
        )(message)

    def list_rems(self, message: "_clientpb__.Listener") -> "_clientpb__.Pipelines":
        return self._channel.unary_unary(
            "/listenerrpc.ListenerRPC/ListRems",
            _clientpb__.Listener.SerializeToString,
            _clientpb__.Pipelines.FromString,
        )(message)

    def health_check_rem(self, message: "_clientpb__.Pipeline") -> "_clientpb__.Empty":
        return self._channel.unary_unary(
            "/listenerrpc.ListenerRPC/HealthCheckRem",
            _clientpb__.Pipeline.SerializeToString,
            _clientpb__.Empty.FromString,
        )(message)

    def rem_agent_ctrl(self, message: "_clientpb__.RemAgent") -> "_clientpb__.Empty":
        return self._channel.unary_unary(
            "/listenerrpc.ListenerRPC/RemAgentCtrl",
            _clientpb__.RemAgent.SerializeToString,
            _clientpb__.Empty.FromString,
        )(message)

    def rem_agent_stop(self, message: "_clientpb__.RemAgent") -> "_clientpb__.Empty":
        return self._channel.unary_unary(
            "/listenerrpc.ListenerRPC/RemAgentStop",
            _clientpb__.RemAgent.SerializeToString,
            _clientpb__.Empty.FromString,
        )(message)

    def rem_agent_log(self, message: "_clientpb__.RemAgent") -> "_clientpb__.RemLog":
        return self._channel.unary_unary(
            "/listenerrpc.ListenerRPC/RemAgentLog",
            _clientpb__.RemAgent.SerializeToString,
            _clientpb__.RemLog.FromString,
        )(message)

    def new_profile(self, message: "_clientpb__.Profile") -> "_clientpb__.Empty":
        """
        generator
        """

        return self._channel.unary_unary(
            "/listenerrpc.ListenerRPC/NewProfile",
            _clientpb__.Profile.SerializeToString,
            _clientpb__.Empty.FromString,
        )(message)

    def find_artifact(self, message: "_clientpb__.Artifact") -> "_clientpb__.Artifact":
        return self._channel.unary_unary(
            "/listenerrpc.ListenerRPC/FindArtifact",
            _clientpb__.Artifact.SerializeToString,
            _clientpb__.Artifact.FromString,
        )(message)

    def build(self, message: "_clientpb__.BuildConfig") -> "_clientpb__.Artifact":
        return self._channel.unary_unary(
            "/listenerrpc.ListenerRPC/Build",
            _clientpb__.BuildConfig.SerializeToString,
            _clientpb__.Artifact.FromString,
        )(message)

    def sync_build(self, message: "_clientpb__.BuildConfig") -> "_clientpb__.Artifact":
        return self._channel.unary_unary(
            "/listenerrpc.ListenerRPC/SyncBuild",
            _clientpb__.BuildConfig.SerializeToString,
            _clientpb__.Artifact.FromString,
        )(message)

    def build_log(self, message: "_clientpb__.Artifact") -> "_clientpb__.Artifact":
        return self._channel.unary_unary(
            "/listenerrpc.ListenerRPC/BuildLog",
            _clientpb__.Artifact.SerializeToString,
            _clientpb__.Artifact.FromString,
        )(message)

    def check_source(
        self, message: "_clientpb__.BuildConfig"
    ) -> "_clientpb__.BuildConfig":
        return self._channel.unary_unary(
            "/listenerrpc.ListenerRPC/CheckSource",
            _clientpb__.BuildConfig.SerializeToString,
            _clientpb__.BuildConfig.FromString,
        )(message)

    def generate_self_cert(
        self, message: "_clientpb__.Pipeline"
    ) -> "_clientpb__.Empty":
        """
        cert
        """

        return self._channel.unary_unary(
            "/listenerrpc.ListenerRPC/GenerateSelfCert",
            _clientpb__.Pipeline.SerializeToString,
            _clientpb__.Empty.FromString,
        )(message)

    def generate_acme_cert(
        self, message: "_clientpb__.Pipeline"
    ) -> "_clientpb__.Empty":
        return self._channel.unary_unary(
            "/listenerrpc.ListenerRPC/GenerateAcmeCert",
            _clientpb__.Pipeline.SerializeToString,
            _clientpb__.Empty.FromString,
        )(message)

    def save_acme_cert(self, message: "_clientpb__.Pipeline") -> "_clientpb__.Empty":
        return self._channel.unary_unary(
            "/listenerrpc.ListenerRPC/SaveAcmeCert",
            _clientpb__.Pipeline.SerializeToString,
            _clientpb__.Empty.FromString,
        )(message)

    def get_artifact(self, message: "_clientpb__.Artifact") -> "_clientpb__.Artifact":
        """
        rpc ListenerCtrl(clientpb.CtrlStatus) returns (stream clientpb.CtrlPipeline);
        """

        return self._channel.unary_unary(
            "/listenerrpc.ListenerRPC/GetArtifact",
            _clientpb__.Artifact.SerializeToString,
            _clientpb__.Artifact.FromString,
        )(message)


class ListenerRpcStub(betterproto2.ServiceStub):
    async def spite_stream(
        self,
        messages: "AsyncIterable[_clientpb__.SpiteResponse] | Iterable[_clientpb__.SpiteResponse]",
        *,
        timeout: "float | None" = None,
        deadline: "Deadline | None" = None,
        metadata: "MetadataLike | None" = None,
    ) -> "AsyncIterator[_clientpb__.SpiteRequest]":
        async for response in self._stream_stream(
            "/listenerrpc.ListenerRPC/SpiteStream",
            messages,
            _clientpb__.SpiteResponse,
            _clientpb__.SpiteRequest,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        ):
            yield response

    async def job_stream(
        self,
        messages: "AsyncIterable[_clientpb__.JobStatus] | Iterable[_clientpb__.JobStatus]",
        *,
        timeout: "float | None" = None,
        deadline: "Deadline | None" = None,
        metadata: "MetadataLike | None" = None,
    ) -> "AsyncIterator[_clientpb__.JobCtrl]":
        async for response in self._stream_stream(
            "/listenerrpc.ListenerRPC/JobStream",
            messages,
            _clientpb__.JobStatus,
            _clientpb__.JobCtrl,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        ):
            yield response

    async def register(
        self,
        message: "_clientpb__.RegisterSession",
        *,
        timeout: "float | None" = None,
        deadline: "Deadline | None" = None,
        metadata: "MetadataLike | None" = None,
    ) -> "_clientpb__.Empty":
        """
        implant
        """

        return await self._unary_unary(
            "/listenerrpc.ListenerRPC/Register",
            message,
            _clientpb__.Empty,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def sys_info(
        self,
        message: "_modulepb__.SysInfo",
        *,
        timeout: "float | None" = None,
        deadline: "Deadline | None" = None,
        metadata: "MetadataLike | None" = None,
    ) -> "_clientpb__.Empty":
        return await self._unary_unary(
            "/listenerrpc.ListenerRPC/SysInfo",
            message,
            _clientpb__.Empty,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def checkin(
        self,
        message: "_modulepb__.Ping",
        *,
        timeout: "float | None" = None,
        deadline: "Deadline | None" = None,
        metadata: "MetadataLike | None" = None,
    ) -> "_clientpb__.Empty":
        return await self._unary_unary(
            "/listenerrpc.ListenerRPC/Checkin",
            message,
            _clientpb__.Empty,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def init_bind_session(
        self,
        message: "_modulepb__.Request",
        *,
        timeout: "float | None" = None,
        deadline: "Deadline | None" = None,
        metadata: "MetadataLike | None" = None,
    ) -> "_clientpb__.Empty":
        return await self._unary_unary(
            "/listenerrpc.ListenerRPC/InitBindSession",
            message,
            _clientpb__.Empty,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def register_listener(
        self,
        message: "_clientpb__.RegisterListener",
        *,
        timeout: "float | None" = None,
        deadline: "Deadline | None" = None,
        metadata: "MetadataLike | None" = None,
    ) -> "_clientpb__.Empty":
        """
        pipeline
        """

        return await self._unary_unary(
            "/listenerrpc.ListenerRPC/RegisterListener",
            message,
            _clientpb__.Empty,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def register_pipeline(
        self,
        message: "_clientpb__.Pipeline",
        *,
        timeout: "float | None" = None,
        deadline: "Deadline | None" = None,
        metadata: "MetadataLike | None" = None,
    ) -> "_clientpb__.Empty":
        return await self._unary_unary(
            "/listenerrpc.ListenerRPC/RegisterPipeline",
            message,
            _clientpb__.Empty,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def start_pipeline(
        self,
        message: "_clientpb__.CtrlPipeline",
        *,
        timeout: "float | None" = None,
        deadline: "Deadline | None" = None,
        metadata: "MetadataLike | None" = None,
    ) -> "_clientpb__.Empty":
        return await self._unary_unary(
            "/listenerrpc.ListenerRPC/StartPipeline",
            message,
            _clientpb__.Empty,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def stop_pipeline(
        self,
        message: "_clientpb__.CtrlPipeline",
        *,
        timeout: "float | None" = None,
        deadline: "Deadline | None" = None,
        metadata: "MetadataLike | None" = None,
    ) -> "_clientpb__.Empty":
        return await self._unary_unary(
            "/listenerrpc.ListenerRPC/StopPipeline",
            message,
            _clientpb__.Empty,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def delete_pipeline(
        self,
        message: "_clientpb__.CtrlPipeline",
        *,
        timeout: "float | None" = None,
        deadline: "Deadline | None" = None,
        metadata: "MetadataLike | None" = None,
    ) -> "_clientpb__.Empty":
        return await self._unary_unary(
            "/listenerrpc.ListenerRPC/DeletePipeline",
            message,
            _clientpb__.Empty,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def list_pipelines(
        self,
        message: "_clientpb__.Listener",
        *,
        timeout: "float | None" = None,
        deadline: "Deadline | None" = None,
        metadata: "MetadataLike | None" = None,
    ) -> "_clientpb__.Pipelines":
        return await self._unary_unary(
            "/listenerrpc.ListenerRPC/ListPipelines",
            message,
            _clientpb__.Pipelines,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def sync_pipeline(
        self,
        message: "_clientpb__.Pipeline",
        *,
        timeout: "float | None" = None,
        deadline: "Deadline | None" = None,
        metadata: "MetadataLike | None" = None,
    ) -> "_clientpb__.Empty":
        return await self._unary_unary(
            "/listenerrpc.ListenerRPC/SyncPipeline",
            message,
            _clientpb__.Empty,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def register_website(
        self,
        message: "_clientpb__.Pipeline",
        *,
        timeout: "float | None" = None,
        deadline: "Deadline | None" = None,
        metadata: "MetadataLike | None" = None,
    ) -> "_clientpb__.Empty":
        """
        website
        """

        return await self._unary_unary(
            "/listenerrpc.ListenerRPC/RegisterWebsite",
            message,
            _clientpb__.Empty,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def start_website(
        self,
        message: "_clientpb__.CtrlPipeline",
        *,
        timeout: "float | None" = None,
        deadline: "Deadline | None" = None,
        metadata: "MetadataLike | None" = None,
    ) -> "_clientpb__.Empty":
        return await self._unary_unary(
            "/listenerrpc.ListenerRPC/StartWebsite",
            message,
            _clientpb__.Empty,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def stop_website(
        self,
        message: "_clientpb__.CtrlPipeline",
        *,
        timeout: "float | None" = None,
        deadline: "Deadline | None" = None,
        metadata: "MetadataLike | None" = None,
    ) -> "_clientpb__.Empty":
        return await self._unary_unary(
            "/listenerrpc.ListenerRPC/StopWebsite",
            message,
            _clientpb__.Empty,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def delete_website(
        self,
        message: "_clientpb__.CtrlPipeline",
        *,
        timeout: "float | None" = None,
        deadline: "Deadline | None" = None,
        metadata: "MetadataLike | None" = None,
    ) -> "_clientpb__.Empty":
        return await self._unary_unary(
            "/listenerrpc.ListenerRPC/DeleteWebsite",
            message,
            _clientpb__.Empty,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def list_websites(
        self,
        message: "_clientpb__.Listener",
        *,
        timeout: "float | None" = None,
        deadline: "Deadline | None" = None,
        metadata: "MetadataLike | None" = None,
    ) -> "_clientpb__.Pipelines":
        return await self._unary_unary(
            "/listenerrpc.ListenerRPC/ListWebsites",
            message,
            _clientpb__.Pipelines,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def list_web_content(
        self,
        message: "_clientpb__.Website",
        *,
        timeout: "float | None" = None,
        deadline: "Deadline | None" = None,
        metadata: "MetadataLike | None" = None,
    ) -> "_clientpb__.WebContents":
        return await self._unary_unary(
            "/listenerrpc.ListenerRPC/ListWebContent",
            message,
            _clientpb__.WebContents,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def add_website_content(
        self,
        message: "_clientpb__.Website",
        *,
        timeout: "float | None" = None,
        deadline: "Deadline | None" = None,
        metadata: "MetadataLike | None" = None,
    ) -> "_clientpb__.WebContent":
        return await self._unary_unary(
            "/listenerrpc.ListenerRPC/AddWebsiteContent",
            message,
            _clientpb__.WebContent,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def update_website_content(
        self,
        message: "_clientpb__.WebContent",
        *,
        timeout: "float | None" = None,
        deadline: "Deadline | None" = None,
        metadata: "MetadataLike | None" = None,
    ) -> "_clientpb__.WebContent":
        return await self._unary_unary(
            "/listenerrpc.ListenerRPC/UpdateWebsiteContent",
            message,
            _clientpb__.WebContent,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def remove_website_content(
        self,
        message: "_clientpb__.WebContent",
        *,
        timeout: "float | None" = None,
        deadline: "Deadline | None" = None,
        metadata: "MetadataLike | None" = None,
    ) -> "_clientpb__.Empty":
        return await self._unary_unary(
            "/listenerrpc.ListenerRPC/RemoveWebsiteContent",
            message,
            _clientpb__.Empty,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def register_rem(
        self,
        message: "_clientpb__.Pipeline",
        *,
        timeout: "float | None" = None,
        deadline: "Deadline | None" = None,
        metadata: "MetadataLike | None" = None,
    ) -> "_clientpb__.Empty":
        """
        rem
        """

        return await self._unary_unary(
            "/listenerrpc.ListenerRPC/RegisterRem",
            message,
            _clientpb__.Empty,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def start_rem(
        self,
        message: "_clientpb__.CtrlPipeline",
        *,
        timeout: "float | None" = None,
        deadline: "Deadline | None" = None,
        metadata: "MetadataLike | None" = None,
    ) -> "_clientpb__.Empty":
        return await self._unary_unary(
            "/listenerrpc.ListenerRPC/StartRem",
            message,
            _clientpb__.Empty,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def stop_rem(
        self,
        message: "_clientpb__.CtrlPipeline",
        *,
        timeout: "float | None" = None,
        deadline: "Deadline | None" = None,
        metadata: "MetadataLike | None" = None,
    ) -> "_clientpb__.Empty":
        return await self._unary_unary(
            "/listenerrpc.ListenerRPC/StopRem",
            message,
            _clientpb__.Empty,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def delete_rem(
        self,
        message: "_clientpb__.CtrlPipeline",
        *,
        timeout: "float | None" = None,
        deadline: "Deadline | None" = None,
        metadata: "MetadataLike | None" = None,
    ) -> "_clientpb__.Empty":
        return await self._unary_unary(
            "/listenerrpc.ListenerRPC/DeleteRem",
            message,
            _clientpb__.Empty,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def list_rems(
        self,
        message: "_clientpb__.Listener",
        *,
        timeout: "float | None" = None,
        deadline: "Deadline | None" = None,
        metadata: "MetadataLike | None" = None,
    ) -> "_clientpb__.Pipelines":
        return await self._unary_unary(
            "/listenerrpc.ListenerRPC/ListRems",
            message,
            _clientpb__.Pipelines,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def health_check_rem(
        self,
        message: "_clientpb__.Pipeline",
        *,
        timeout: "float | None" = None,
        deadline: "Deadline | None" = None,
        metadata: "MetadataLike | None" = None,
    ) -> "_clientpb__.Empty":
        return await self._unary_unary(
            "/listenerrpc.ListenerRPC/HealthCheckRem",
            message,
            _clientpb__.Empty,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def rem_agent_ctrl(
        self,
        message: "_clientpb__.RemAgent",
        *,
        timeout: "float | None" = None,
        deadline: "Deadline | None" = None,
        metadata: "MetadataLike | None" = None,
    ) -> "_clientpb__.Empty":
        return await self._unary_unary(
            "/listenerrpc.ListenerRPC/RemAgentCtrl",
            message,
            _clientpb__.Empty,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def rem_agent_stop(
        self,
        message: "_clientpb__.RemAgent",
        *,
        timeout: "float | None" = None,
        deadline: "Deadline | None" = None,
        metadata: "MetadataLike | None" = None,
    ) -> "_clientpb__.Empty":
        return await self._unary_unary(
            "/listenerrpc.ListenerRPC/RemAgentStop",
            message,
            _clientpb__.Empty,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def rem_agent_log(
        self,
        message: "_clientpb__.RemAgent",
        *,
        timeout: "float | None" = None,
        deadline: "Deadline | None" = None,
        metadata: "MetadataLike | None" = None,
    ) -> "_clientpb__.RemLog":
        return await self._unary_unary(
            "/listenerrpc.ListenerRPC/RemAgentLog",
            message,
            _clientpb__.RemLog,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def new_profile(
        self,
        message: "_clientpb__.Profile",
        *,
        timeout: "float | None" = None,
        deadline: "Deadline | None" = None,
        metadata: "MetadataLike | None" = None,
    ) -> "_clientpb__.Empty":
        """
        generator
        """

        return await self._unary_unary(
            "/listenerrpc.ListenerRPC/NewProfile",
            message,
            _clientpb__.Empty,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def find_artifact(
        self,
        message: "_clientpb__.Artifact",
        *,
        timeout: "float | None" = None,
        deadline: "Deadline | None" = None,
        metadata: "MetadataLike | None" = None,
    ) -> "_clientpb__.Artifact":
        return await self._unary_unary(
            "/listenerrpc.ListenerRPC/FindArtifact",
            message,
            _clientpb__.Artifact,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def build(
        self,
        message: "_clientpb__.BuildConfig",
        *,
        timeout: "float | None" = None,
        deadline: "Deadline | None" = None,
        metadata: "MetadataLike | None" = None,
    ) -> "_clientpb__.Artifact":
        return await self._unary_unary(
            "/listenerrpc.ListenerRPC/Build",
            message,
            _clientpb__.Artifact,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def sync_build(
        self,
        message: "_clientpb__.BuildConfig",
        *,
        timeout: "float | None" = None,
        deadline: "Deadline | None" = None,
        metadata: "MetadataLike | None" = None,
    ) -> "_clientpb__.Artifact":
        return await self._unary_unary(
            "/listenerrpc.ListenerRPC/SyncBuild",
            message,
            _clientpb__.Artifact,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def build_log(
        self,
        message: "_clientpb__.Artifact",
        *,
        timeout: "float | None" = None,
        deadline: "Deadline | None" = None,
        metadata: "MetadataLike | None" = None,
    ) -> "_clientpb__.Artifact":
        return await self._unary_unary(
            "/listenerrpc.ListenerRPC/BuildLog",
            message,
            _clientpb__.Artifact,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def check_source(
        self,
        message: "_clientpb__.BuildConfig",
        *,
        timeout: "float | None" = None,
        deadline: "Deadline | None" = None,
        metadata: "MetadataLike | None" = None,
    ) -> "_clientpb__.BuildConfig":
        return await self._unary_unary(
            "/listenerrpc.ListenerRPC/CheckSource",
            message,
            _clientpb__.BuildConfig,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def generate_self_cert(
        self,
        message: "_clientpb__.Pipeline",
        *,
        timeout: "float | None" = None,
        deadline: "Deadline | None" = None,
        metadata: "MetadataLike | None" = None,
    ) -> "_clientpb__.Empty":
        """
        cert
        """

        return await self._unary_unary(
            "/listenerrpc.ListenerRPC/GenerateSelfCert",
            message,
            _clientpb__.Empty,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def generate_acme_cert(
        self,
        message: "_clientpb__.Pipeline",
        *,
        timeout: "float | None" = None,
        deadline: "Deadline | None" = None,
        metadata: "MetadataLike | None" = None,
    ) -> "_clientpb__.Empty":
        return await self._unary_unary(
            "/listenerrpc.ListenerRPC/GenerateAcmeCert",
            message,
            _clientpb__.Empty,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def save_acme_cert(
        self,
        message: "_clientpb__.Pipeline",
        *,
        timeout: "float | None" = None,
        deadline: "Deadline | None" = None,
        metadata: "MetadataLike | None" = None,
    ) -> "_clientpb__.Empty":
        return await self._unary_unary(
            "/listenerrpc.ListenerRPC/SaveAcmeCert",
            message,
            _clientpb__.Empty,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def get_artifact(
        self,
        message: "_clientpb__.Artifact",
        *,
        timeout: "float | None" = None,
        deadline: "Deadline | None" = None,
        metadata: "MetadataLike | None" = None,
    ) -> "_clientpb__.Artifact":
        """
        rpc ListenerCtrl(clientpb.CtrlStatus) returns (stream clientpb.CtrlPipeline);
        """

        return await self._unary_unary(
            "/listenerrpc.ListenerRPC/GetArtifact",
            message,
            _clientpb__.Artifact,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )


from .. import clientpb as _clientpb__
from .. import modulepb as _modulepb__
