# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: implant/implantpb/implant.proto
# plugin: python-betterproto2
# This file has been @generated

__all__ = (
    "Empty",
    "Spite",
    "Spites",
    "Status",
)

import typing

import betterproto2
import pydantic
from pydantic import model_validator
from pydantic.dataclasses import dataclass

from ..message_pool import default_message_pool

_COMPILER_VERSION = "0.8.0"
betterproto2.check_compiler_version(_COMPILER_VERSION)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class Empty(betterproto2.Message):
    pass


default_message_pool.register_message("implantpb", "Empty", Empty)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class Spite(betterproto2.Message):
    """
    implant call and back data

    Oneofs:
        - body:
    """

    name: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        1, betterproto2.TYPE_STRING
    )

    task_id: "typing.Annotated[int, pydantic.Field(ge=0, le=2**32 - 1)]" = (
        betterproto2.field(2, betterproto2.TYPE_UINT32)
    )

    timeout: "typing.Annotated[int, pydantic.Field(ge=0, le=2**64 - 1)]" = (
        betterproto2.field(4, betterproto2.TYPE_UINT64)
    )
    """
     bool  async = 3;
    """

    error: "typing.Annotated[int, pydantic.Field(ge=0, le=2**32 - 1)]" = (
        betterproto2.field(5, betterproto2.TYPE_UINT32)
    )

    status: "Status | None" = betterproto2.field(
        6, betterproto2.TYPE_MESSAGE, optional=True
    )

    empty: "Empty | None" = betterproto2.field(
        10, betterproto2.TYPE_MESSAGE, optional=True, group="body"
    )

    block: "_modulepb__.Block | None" = betterproto2.field(
        11, betterproto2.TYPE_MESSAGE, optional=True, group="body"
    )

    ack: "_modulepb__.Ack | None" = betterproto2.field(
        13, betterproto2.TYPE_MESSAGE, optional=True, group="body"
    )

    task: "_modulepb__.TaskCtrl | None" = betterproto2.field(
        14, betterproto2.TYPE_MESSAGE, optional=True, group="body"
    )

    sleep_request: "_modulepb__.Timer | None" = betterproto2.field(
        15, betterproto2.TYPE_MESSAGE, optional=True, group="body"
    )

    init: "_modulepb__.Init | None" = betterproto2.field(
        16, betterproto2.TYPE_MESSAGE, optional=True, group="body"
    )

    switch: "_modulepb__.Switch | None" = betterproto2.field(
        17, betterproto2.TYPE_MESSAGE, optional=True, group="body"
    )

    task_info: "_modulepb__.TaskInfo | None" = betterproto2.field(
        18, betterproto2.TYPE_MESSAGE, optional=True, group="body"
    )

    task_list: "_modulepb__.TaskListResponse | None" = betterproto2.field(
        19, betterproto2.TYPE_MESSAGE, optional=True, group="body"
    )

    sysinfo: "_modulepb__.SysInfo | None" = betterproto2.field(
        20, betterproto2.TYPE_MESSAGE, optional=True, group="body"
    )

    register: "_modulepb__.Register | None" = betterproto2.field(
        21, betterproto2.TYPE_MESSAGE, optional=True, group="body"
    )

    ping: "_modulepb__.Ping | None" = betterproto2.field(
        22, betterproto2.TYPE_MESSAGE, optional=True, group="body"
    )

    suicide: "_modulepb__.Suicide | None" = betterproto2.field(
        23, betterproto2.TYPE_MESSAGE, optional=True, group="body"
    )

    request: "_modulepb__.Request | None" = betterproto2.field(
        24, betterproto2.TYPE_MESSAGE, optional=True, group="body"
    )

    response: "_modulepb__.Response | None" = betterproto2.field(
        25, betterproto2.TYPE_MESSAGE, optional=True, group="body"
    )

    execute_binary: "_modulepb__.ExecuteBinary | None" = betterproto2.field(
        26, betterproto2.TYPE_MESSAGE, optional=True, group="body"
    )

    binary_response: "_modulepb__.BinaryResponse | None" = betterproto2.field(
        27, betterproto2.TYPE_MESSAGE, optional=True, group="body"
    )

    load_module: "_modulepb__.LoadModule | None" = betterproto2.field(
        31, betterproto2.TYPE_MESSAGE, optional=True, group="body"
    )

    modules: "_modulepb__.Modules | None" = betterproto2.field(
        32, betterproto2.TYPE_MESSAGE, optional=True, group="body"
    )

    load_addon: "_modulepb__.LoadAddon | None" = betterproto2.field(
        35, betterproto2.TYPE_MESSAGE, optional=True, group="body"
    )

    addons: "_modulepb__.Addons | None" = betterproto2.field(
        36, betterproto2.TYPE_MESSAGE, optional=True, group="body"
    )

    execute_addon: "_modulepb__.ExecuteAddon | None" = betterproto2.field(
        37, betterproto2.TYPE_MESSAGE, optional=True, group="body"
    )

    wmi_request: "_modulepb__.WmiQueryRequest | None" = betterproto2.field(
        38, betterproto2.TYPE_MESSAGE, optional=True, group="body"
    )

    wmi_method_request: "_modulepb__.WmiMethodRequest | None" = betterproto2.field(
        39, betterproto2.TYPE_MESSAGE, optional=True, group="body"
    )

    ls_response: "_modulepb__.LsResponse | None" = betterproto2.field(
        101, betterproto2.TYPE_MESSAGE, optional=True, group="body"
    )

    chown_request: "_modulepb__.ChownRequest | None" = betterproto2.field(
        102, betterproto2.TYPE_MESSAGE, optional=True, group="body"
    )

    exec_request: "_modulepb__.ExecRequest | None" = betterproto2.field(
        104, betterproto2.TYPE_MESSAGE, optional=True, group="body"
    )

    exec_response: "_modulepb__.ExecResponse | None" = betterproto2.field(
        105, betterproto2.TYPE_MESSAGE, optional=True, group="body"
    )

    upload_request: "_modulepb__.UploadRequest | None" = betterproto2.field(
        106, betterproto2.TYPE_MESSAGE, optional=True, group="body"
    )

    download_request: "_modulepb__.DownloadRequest | None" = betterproto2.field(
        107, betterproto2.TYPE_MESSAGE, optional=True, group="body"
    )

    download_response: "_modulepb__.DownloadResponse | None" = betterproto2.field(
        108, betterproto2.TYPE_MESSAGE, optional=True, group="body"
    )

    netstat_response: "_modulepb__.NetstatResponse | None" = betterproto2.field(
        109, betterproto2.TYPE_MESSAGE, optional=True, group="body"
    )

    ps_response: "_modulepb__.PsResponse | None" = betterproto2.field(
        110, betterproto2.TYPE_MESSAGE, optional=True, group="body"
    )

    bypass_request: "_modulepb__.BypassRequest | None" = betterproto2.field(
        111, betterproto2.TYPE_MESSAGE, optional=True, group="body"
    )

    execute_command: "_modulepb__.ExecuteCommand | None" = betterproto2.field(
        112, betterproto2.TYPE_MESSAGE, optional=True, group="body"
    )

    ifconfig_response: "_modulepb__.IfconfigResponse | None" = betterproto2.field(
        118, betterproto2.TYPE_MESSAGE, optional=True, group="body"
    )

    curl_request: "_modulepb__.CurlRequest | None" = betterproto2.field(
        119, betterproto2.TYPE_MESSAGE, optional=True, group="body"
    )

    key_exchange_request: "_modulepb__.KeyExchangeRequest | None" = betterproto2.field(
        120, betterproto2.TYPE_MESSAGE, optional=True, group="body"
    )

    key_exchange_response: "_modulepb__.KeyExchangeResponse | None" = (
        betterproto2.field(121, betterproto2.TYPE_MESSAGE, optional=True, group="body")
    )

    registry_request: "_modulepb__.Registry | None" = betterproto2.field(
        122, betterproto2.TYPE_MESSAGE, optional=True, group="body"
    )

    registry_write_request: "_modulepb__.RegistryWriteRequest | None" = (
        betterproto2.field(123, betterproto2.TYPE_MESSAGE, optional=True, group="body")
    )

    schedule_request: "_modulepb__.TaskSchedule | None" = betterproto2.field(
        124, betterproto2.TYPE_MESSAGE, optional=True, group="body"
    )

    schedules_response: "_modulepb__.TaskSchedulesResponse | None" = betterproto2.field(
        125, betterproto2.TYPE_MESSAGE, optional=True, group="body"
    )

    schedule_response: "_modulepb__.TaskSchedule | None" = betterproto2.field(
        126, betterproto2.TYPE_MESSAGE, optional=True, group="body"
    )

    service_request: "_modulepb__.ServiceConfig | None" = betterproto2.field(
        127, betterproto2.TYPE_MESSAGE, optional=True, group="body"
    )

    services_response: "_modulepb__.ServicesResponse | None" = betterproto2.field(
        128, betterproto2.TYPE_MESSAGE, optional=True, group="body"
    )

    service_response: "_modulepb__.Service | None" = betterproto2.field(
        129, betterproto2.TYPE_MESSAGE, optional=True, group="body"
    )

    runas_request: "_modulepb__.RunAsRequest | None" = betterproto2.field(
        130, betterproto2.TYPE_MESSAGE, optional=True, group="body"
    )

    getsystem: "_modulepb__.GetSystem | None" = betterproto2.field(
        131, betterproto2.TYPE_MESSAGE, optional=True, group="body"
    )

    inject: "_modulepb__.Inject | None" = betterproto2.field(
        132, betterproto2.TYPE_MESSAGE, optional=True, group="body"
    )

    pipe_request: "_modulepb__.Pipe | None" = betterproto2.field(
        140, betterproto2.TYPE_MESSAGE, optional=True, group="body"
    )

    ffmpeg_request: "_modulepb__.FFmpegRequest | None" = betterproto2.field(
        150, betterproto2.TYPE_MESSAGE, optional=True, group="body"
    )

    shell_request: "_modulepb__.ShellRequest | None" = betterproto2.field(
        151, betterproto2.TYPE_MESSAGE, optional=True, group="body"
    )

    shell_response: "_modulepb__.ShellResponse | None" = betterproto2.field(
        152, betterproto2.TYPE_MESSAGE, optional=True, group="body"
    )

    @model_validator(mode="after")
    def check_oneof(cls, values):
        return cls._validate_field_groups(values)


default_message_pool.register_message("implantpb", "Spite", Spite)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class Spites(betterproto2.Message):
    spites: "list[Spite]" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, repeated=True
    )


default_message_pool.register_message("implantpb", "Spites", Spites)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class Status(betterproto2.Message):
    task_id: "typing.Annotated[int, pydantic.Field(ge=0, le=2**32 - 1)]" = (
        betterproto2.field(1, betterproto2.TYPE_UINT32)
    )

    status: "typing.Annotated[int, pydantic.Field(ge=-2**31, le=2**31 - 1)]" = (
        betterproto2.field(2, betterproto2.TYPE_INT32)
    )
    """
    unexcept error
    """

    error: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        3, betterproto2.TYPE_STRING
    )
    """
    std err
    """


default_message_pool.register_message("implantpb", "Status", Status)


from .. import modulepb as _modulepb__
