from typing import Any, Callable, Awaitable
from .client import MaliceClient

class MaliceSession:
    def __init__(self, client: MaliceClient, session_id: str): ...


    # Dynamically forwarded methods from MaliceRpcStub
    # Basic methods
    async def login_client(message: '_clientpb__.LoginReq', *, timeout: 'float | None' = None, deadline: 'Deadline | None' = None, metadata: 'MetadataLike | None' = None) -> '_clientpb__.Client': ...

    async def get_basic(message: '_clientpb__.Empty | None' = None, *, timeout: 'float | None' = None, deadline: 'Deadline | None' = None, metadata: 'MetadataLike | None' = None) -> '_clientpb__.Basic': ...

    async def get_clients(message: '_clientpb__.Empty | None' = None, *, timeout: 'float | None' = None, deadline: 'Deadline | None' = None, metadata: 'MetadataLike | None' = None) -> '_clientpb__.Clients': ...

    async def get_sessions(message: '_clientpb__.SessionRequest', *, timeout: 'float | None' = None, deadline: 'Deadline | None' = None, metadata: 'MetadataLike | None' = None) -> '_clientpb__.Sessions': ...

    async def get_session(message: '_clientpb__.SessionRequest', *, timeout: 'float | None' = None, deadline: 'Deadline | None' = None, metadata: 'MetadataLike | None' = None) -> '_clientpb__.Session': ...

    async def get_session_history(message: '_clientpb__.Int', *, timeout: 'float | None' = None, deadline: 'Deadline | None' = None, metadata: 'MetadataLike | None' = None) -> '_clientpb__.TasksContext': ...

    async def get_listeners(message: '_clientpb__.Empty | None' = None, *, timeout: 'float | None' = None, deadline: 'Deadline | None' = None, metadata: 'MetadataLike | None' = None) -> '_clientpb__.Listeners': ...

    async def get_audit(message: '_clientpb__.SessionRequest', *, timeout: 'float | None' = None, deadline: 'Deadline | None' = None, metadata: 'MetadataLike | None' = None) -> '_clientpb__.Audits': ...

    # Task methods
    async def get_tasks(message: '_clientpb__.TaskRequest', *, timeout: 'float | None' = None, deadline: 'Deadline | None' = None, metadata: 'MetadataLike | None' = None) -> '_clientpb__.Tasks': ...

    async def get_task_content(message: '_clientpb__.Task', *, timeout: 'float | None' = None, deadline: 'Deadline | None' = None, metadata: 'MetadataLike | None' = None) -> '_clientpb__.TaskContext': ...

    async def wait_task_content(message: '_clientpb__.Task', *, timeout: 'float | None' = None, deadline: 'Deadline | None' = None, metadata: 'MetadataLike | None' = None) -> '_clientpb__.TaskContext': ...

    async def wait_task_finish(message: '_clientpb__.Task', *, timeout: 'float | None' = None, deadline: 'Deadline | None' = None, metadata: 'MetadataLike | None' = None) -> '_clientpb__.TaskContext': ...

    async def list_tasks(message: '_modulepb__.Request', *, timeout: 'float | None' = None, deadline: 'Deadline | None' = None, metadata: 'MetadataLike | None' = None) -> '_clientpb__.Task': ...

    async def query_task(message: '_modulepb__.TaskCtrl', *, timeout: 'float | None' = None, deadline: 'Deadline | None' = None, metadata: 'MetadataLike | None' = None) -> '_clientpb__.Task': ...

    async def cancel_task(message: '_modulepb__.TaskCtrl', *, timeout: 'float | None' = None, deadline: 'Deadline | None' = None, metadata: 'MetadataLike | None' = None) -> '_clientpb__.Task': ...

    # File methods
    async def get_files(message: '_clientpb__.Session', *, timeout: 'float | None' = None, deadline: 'Deadline | None' = None, metadata: 'MetadataLike | None' = None) -> '_clientpb__.Files': ...

    async def upload(message: '_modulepb__.UploadRequest', *, timeout: 'float | None' = None, deadline: 'Deadline | None' = None, metadata: 'MetadataLike | None' = None) -> '_clientpb__.Task': ...

    async def download(message: '_modulepb__.DownloadRequest', *, timeout: 'float | None' = None, deadline: 'Deadline | None' = None, metadata: 'MetadataLike | None' = None) -> '_clientpb__.Task': ...

    async def download_dir(message: '_modulepb__.DownloadRequest', *, timeout: 'float | None' = None, deadline: 'Deadline | None' = None, metadata: 'MetadataLike | None' = None) -> '_clientpb__.Task': ...

    async def sync(message: '_clientpb__.Sync', *, timeout: 'float | None' = None, deadline: 'Deadline | None' = None, metadata: 'MetadataLike | None' = None) -> '_clientpb__.Context': ...

    async def download_artifact(message: '_clientpb__.Artifact', *, timeout: 'float | None' = None, deadline: 'Deadline | None' = None, metadata: 'MetadataLike | None' = None) -> '_clientpb__.Artifact': ...

    async def upload_artifact(message: '_clientpb__.Artifact', *, timeout: 'float | None' = None, deadline: 'Deadline | None' = None, metadata: 'MetadataLike | None' = None) -> '_clientpb__.Artifact': ...

    async def download_certificate(message: '_clientpb__.Cert', *, timeout: 'float | None' = None, deadline: 'Deadline | None' = None, metadata: 'MetadataLike | None' = None) -> '_clientpb__.Tls': ...

    # System methods
    async def pwd(message: '_modulepb__.Request', *, timeout: 'float | None' = None, deadline: 'Deadline | None' = None, metadata: 'MetadataLike | None' = None) -> '_clientpb__.Task': ...

    async def ls(message: '_modulepb__.Request', *, timeout: 'float | None' = None, deadline: 'Deadline | None' = None, metadata: 'MetadataLike | None' = None) -> '_clientpb__.Task': ...

    async def cd(message: '_modulepb__.Request', *, timeout: 'float | None' = None, deadline: 'Deadline | None' = None, metadata: 'MetadataLike | None' = None) -> '_clientpb__.Task': ...

    async def rm(message: '_modulepb__.Request', *, timeout: 'float | None' = None, deadline: 'Deadline | None' = None, metadata: 'MetadataLike | None' = None) -> '_clientpb__.Task': ...

    async def mv(message: '_modulepb__.Request', *, timeout: 'float | None' = None, deadline: 'Deadline | None' = None, metadata: 'MetadataLike | None' = None) -> '_clientpb__.Task': ...

    async def cp(message: '_modulepb__.Request', *, timeout: 'float | None' = None, deadline: 'Deadline | None' = None, metadata: 'MetadataLike | None' = None) -> '_clientpb__.Task': ...

    async def cat(message: '_modulepb__.Request', *, timeout: 'float | None' = None, deadline: 'Deadline | None' = None, metadata: 'MetadataLike | None' = None) -> '_clientpb__.Task': ...

    async def mkdir(message: '_modulepb__.Request', *, timeout: 'float | None' = None, deadline: 'Deadline | None' = None, metadata: 'MetadataLike | None' = None) -> '_clientpb__.Task': ...

    async def chmod(message: '_modulepb__.Request', *, timeout: 'float | None' = None, deadline: 'Deadline | None' = None, metadata: 'MetadataLike | None' = None) -> '_clientpb__.Task': ...

    async def chown(message: '_modulepb__.ChownRequest', *, timeout: 'float | None' = None, deadline: 'Deadline | None' = None, metadata: 'MetadataLike | None' = None) -> '_clientpb__.Task': ...

    async def kill(message: '_modulepb__.Request', *, timeout: 'float | None' = None, deadline: 'Deadline | None' = None, metadata: 'MetadataLike | None' = None) -> '_clientpb__.Task': ...

    async def ps(message: '_modulepb__.Request', *, timeout: 'float | None' = None, deadline: 'Deadline | None' = None, metadata: 'MetadataLike | None' = None) -> '_clientpb__.Task': ...

    async def netstat(message: '_modulepb__.Request', *, timeout: 'float | None' = None, deadline: 'Deadline | None' = None, metadata: 'MetadataLike | None' = None) -> '_clientpb__.Task': ...

    async def env(message: '_modulepb__.Request', *, timeout: 'float | None' = None, deadline: 'Deadline | None' = None, metadata: 'MetadataLike | None' = None) -> '_clientpb__.Task': ...

    async def set_env(message: '_modulepb__.Request', *, timeout: 'float | None' = None, deadline: 'Deadline | None' = None, metadata: 'MetadataLike | None' = None) -> '_clientpb__.Task': ...

    async def unset_env(message: '_modulepb__.Request', *, timeout: 'float | None' = None, deadline: 'Deadline | None' = None, metadata: 'MetadataLike | None' = None) -> '_clientpb__.Task': ...

    async def whoami(message: '_modulepb__.Request', *, timeout: 'float | None' = None, deadline: 'Deadline | None' = None, metadata: 'MetadataLike | None' = None) -> '_clientpb__.Task': ...

    async def info(message: '_modulepb__.Request', *, timeout: 'float | None' = None, deadline: 'Deadline | None' = None, metadata: 'MetadataLike | None' = None) -> '_clientpb__.Task': ...

    # Execute methods
    async def execute_addon(message: '_modulepb__.ExecuteAddon', *, timeout: 'float | None' = None, deadline: 'Deadline | None' = None, metadata: 'MetadataLike | None' = None) -> '_clientpb__.Task': ...

    async def execute(message: '_modulepb__.ExecRequest', *, timeout: 'float | None' = None, deadline: 'Deadline | None' = None, metadata: 'MetadataLike | None' = None) -> '_clientpb__.Task': ...

    async def execute_spawn(message: '_modulepb__.ExecuteBinary', *, timeout: 'float | None' = None, deadline: 'Deadline | None' = None, metadata: 'MetadataLike | None' = None) -> '_clientpb__.Task': ...

    async def execute_assembly(message: '_modulepb__.ExecuteBinary', *, timeout: 'float | None' = None, deadline: 'Deadline | None' = None, metadata: 'MetadataLike | None' = None) -> '_clientpb__.Task': ...

    async def execute_powerpick(message: '_modulepb__.ExecuteBinary', *, timeout: 'float | None' = None, deadline: 'Deadline | None' = None, metadata: 'MetadataLike | None' = None) -> '_clientpb__.Task': ...

    async def execute_exe(message: '_modulepb__.ExecuteBinary', *, timeout: 'float | None' = None, deadline: 'Deadline | None' = None, metadata: 'MetadataLike | None' = None) -> '_clientpb__.Task': ...

    async def execute_dll(message: '_modulepb__.ExecuteBinary', *, timeout: 'float | None' = None, deadline: 'Deadline | None' = None, metadata: 'MetadataLike | None' = None) -> '_clientpb__.Task': ...

    async def execute_armory(message: '_modulepb__.ExecuteBinary', *, timeout: 'float | None' = None, deadline: 'Deadline | None' = None, metadata: 'MetadataLike | None' = None) -> '_clientpb__.Task': ...

    async def execute_shellcode(message: '_modulepb__.ExecuteBinary', *, timeout: 'float | None' = None, deadline: 'Deadline | None' = None, metadata: 'MetadataLike | None' = None) -> '_clientpb__.Task': ...

    async def execute_bof(message: '_modulepb__.ExecuteBinary', *, timeout: 'float | None' = None, deadline: 'Deadline | None' = None, metadata: 'MetadataLike | None' = None) -> '_clientpb__.Task': ...

    async def execute_local(message: '_modulepb__.ExecuteBinary', *, timeout: 'float | None' = None, deadline: 'Deadline | None' = None, metadata: 'MetadataLike | None' = None) -> '_clientpb__.Task': ...

    async def shellcode_encode(message: '_clientpb__.ShellcodeEncode', *, timeout: 'float | None' = None, deadline: 'Deadline | None' = None, metadata: 'MetadataLike | None' = None) -> '_clientpb__.Bin': ...

    # Other methods
    async def session_manage(message: '_clientpb__.BasicUpdateSession', *, timeout: 'float | None' = None, deadline: 'Deadline | None' = None, metadata: 'MetadataLike | None' = None) -> '_clientpb__.Empty': ...

    async def get_jobs(message: '_clientpb__.Empty | None' = None, *, timeout: 'float | None' = None, deadline: 'Deadline | None' = None, metadata: 'MetadataLike | None' = None) -> '_clientpb__.Jobs': ...

    async def get_context_files(message: '_clientpb__.Session', *, timeout: 'float | None' = None, deadline: 'Deadline | None' = None, metadata: 'MetadataLike | None' = None) -> '_clientpb__.Files': ...

    async def get_all_task_content(message: '_clientpb__.Task', *, timeout: 'float | None' = None, deadline: 'Deadline | None' = None, metadata: 'MetadataLike | None' = None) -> '_clientpb__.TaskContexts': ...

    async def events(message: '_clientpb__.Empty | None' = None, *, timeout: 'float | None' = None, deadline: 'Deadline | None' = None, metadata: 'MetadataLike | None' = None) -> 'AsyncIterator[_clientpb__.Event]': ...

    async def broadcast(message: '_clientpb__.Event', *, timeout: 'float | None' = None, deadline: 'Deadline | None' = None, metadata: 'MetadataLike | None' = None) -> '_clientpb__.Empty': ...

    async def notify(message: '_clientpb__.Event', *, timeout: 'float | None' = None, deadline: 'Deadline | None' = None, metadata: 'MetadataLike | None' = None) -> '_clientpb__.Empty': ...

    async def get_event(message: '_clientpb__.Int', *, timeout: 'float | None' = None, deadline: 'Deadline | None' = None, metadata: 'MetadataLike | None' = None) -> '_clientpb__.Events': ...

    async def session_event(message: '_clientpb__.Event', *, timeout: 'float | None' = None, deadline: 'Deadline | None' = None, metadata: 'MetadataLike | None' = None) -> '_clientpb__.Empty': ...

    async def on_hook(message: '_clientpb__.On', *, timeout: 'float | None' = None, deadline: 'Deadline | None' = None, metadata: 'MetadataLike | None' = None) -> '_clientpb__.Empty': ...

    async def ping(message: '_modulepb__.Ping', *, timeout: 'float | None' = None, deadline: 'Deadline | None' = None, metadata: 'MetadataLike | None' = None) -> '_clientpb__.Task': ...

    async def sleep(message: '_modulepb__.Timer', *, timeout: 'float | None' = None, deadline: 'Deadline | None' = None, metadata: 'MetadataLike | None' = None) -> '_clientpb__.Task': ...

    async def suicide(message: '_modulepb__.Request', *, timeout: 'float | None' = None, deadline: 'Deadline | None' = None, metadata: 'MetadataLike | None' = None) -> '_clientpb__.Task': ...

    async def list_module(message: '_modulepb__.Request', *, timeout: 'float | None' = None, deadline: 'Deadline | None' = None, metadata: 'MetadataLike | None' = None) -> '_clientpb__.Task': ...

    async def load_module(message: '_modulepb__.LoadModule', *, timeout: 'float | None' = None, deadline: 'Deadline | None' = None, metadata: 'MetadataLike | None' = None) -> '_clientpb__.Task': ...

    async def refresh_module(message: '_modulepb__.Request', *, timeout: 'float | None' = None, deadline: 'Deadline | None' = None, metadata: 'MetadataLike | None' = None) -> '_clientpb__.Task': ...

    async def list_addon(message: '_modulepb__.Request', *, timeout: 'float | None' = None, deadline: 'Deadline | None' = None, metadata: 'MetadataLike | None' = None) -> '_clientpb__.Task': ...

    async def load_addon(message: '_modulepb__.LoadAddon', *, timeout: 'float | None' = None, deadline: 'Deadline | None' = None, metadata: 'MetadataLike | None' = None) -> '_clientpb__.Task': ...

    async def clear(message: '_modulepb__.Request', *, timeout: 'float | None' = None, deadline: 'Deadline | None' = None, metadata: 'MetadataLike | None' = None) -> '_clientpb__.Task': ...

    async def switch(message: '_modulepb__.Switch', *, timeout: 'float | None' = None, deadline: 'Deadline | None' = None, metadata: 'MetadataLike | None' = None) -> '_clientpb__.Task': ...

    async def polling(message: '_clientpb__.Polling', *, timeout: 'float | None' = None, deadline: 'Deadline | None' = None, metadata: 'MetadataLike | None' = None) -> '_clientpb__.Empty': ...

    async def enum_drivers(message: '_modulepb__.Request', *, timeout: 'float | None' = None, deadline: 'Deadline | None' = None, metadata: 'MetadataLike | None' = None) -> '_clientpb__.Task': ...

    async def curl(message: '_modulepb__.CurlRequest', *, timeout: 'float | None' = None, deadline: 'Deadline | None' = None, metadata: 'MetadataLike | None' = None) -> '_clientpb__.Task': ...

    async def bypass(message: '_modulepb__.BypassRequest', *, timeout: 'float | None' = None, deadline: 'Deadline | None' = None, metadata: 'MetadataLike | None' = None) -> '_clientpb__.Task': ...

    async def reg_query(message: '_modulepb__.RegistryRequest', *, timeout: 'float | None' = None, deadline: 'Deadline | None' = None, metadata: 'MetadataLike | None' = None) -> '_clientpb__.Task': ...

    async def reg_add(message: '_modulepb__.RegistryWriteRequest', *, timeout: 'float | None' = None, deadline: 'Deadline | None' = None, metadata: 'MetadataLike | None' = None) -> '_clientpb__.Task': ...

    async def reg_delete(message: '_modulepb__.RegistryRequest', *, timeout: 'float | None' = None, deadline: 'Deadline | None' = None, metadata: 'MetadataLike | None' = None) -> '_clientpb__.Task': ...

    async def reg_list_key(message: '_modulepb__.RegistryRequest', *, timeout: 'float | None' = None, deadline: 'Deadline | None' = None, metadata: 'MetadataLike | None' = None) -> '_clientpb__.Task': ...

    async def reg_list_value(message: '_modulepb__.RegistryRequest', *, timeout: 'float | None' = None, deadline: 'Deadline | None' = None, metadata: 'MetadataLike | None' = None) -> '_clientpb__.Task': ...

    async def service_list(message: '_modulepb__.Request', *, timeout: 'float | None' = None, deadline: 'Deadline | None' = None, metadata: 'MetadataLike | None' = None) -> '_clientpb__.Task': ...

    async def service_create(message: '_modulepb__.ServiceRequest', *, timeout: 'float | None' = None, deadline: 'Deadline | None' = None, metadata: 'MetadataLike | None' = None) -> '_clientpb__.Task': ...

    async def service_start(message: '_modulepb__.ServiceRequest', *, timeout: 'float | None' = None, deadline: 'Deadline | None' = None, metadata: 'MetadataLike | None' = None) -> '_clientpb__.Task': ...

    async def service_stop(message: '_modulepb__.ServiceRequest', *, timeout: 'float | None' = None, deadline: 'Deadline | None' = None, metadata: 'MetadataLike | None' = None) -> '_clientpb__.Task': ...

    async def service_query(message: '_modulepb__.ServiceRequest', *, timeout: 'float | None' = None, deadline: 'Deadline | None' = None, metadata: 'MetadataLike | None' = None) -> '_clientpb__.Task': ...

    async def service_delete(message: '_modulepb__.ServiceRequest', *, timeout: 'float | None' = None, deadline: 'Deadline | None' = None, metadata: 'MetadataLike | None' = None) -> '_clientpb__.Task': ...

    async def task_schd_list(message: '_modulepb__.Request', *, timeout: 'float | None' = None, deadline: 'Deadline | None' = None, metadata: 'MetadataLike | None' = None) -> '_clientpb__.Task': ...

    async def task_schd_create(message: '_modulepb__.TaskScheduleRequest', *, timeout: 'float | None' = None, deadline: 'Deadline | None' = None, metadata: 'MetadataLike | None' = None) -> '_clientpb__.Task': ...

    async def task_schd_start(message: '_modulepb__.TaskScheduleRequest', *, timeout: 'float | None' = None, deadline: 'Deadline | None' = None, metadata: 'MetadataLike | None' = None) -> '_clientpb__.Task': ...

    async def task_schd_stop(message: '_modulepb__.TaskScheduleRequest', *, timeout: 'float | None' = None, deadline: 'Deadline | None' = None, metadata: 'MetadataLike | None' = None) -> '_clientpb__.Task': ...

    async def task_schd_delete(message: '_modulepb__.TaskScheduleRequest', *, timeout: 'float | None' = None, deadline: 'Deadline | None' = None, metadata: 'MetadataLike | None' = None) -> '_clientpb__.Task': ...

    async def task_schd_query(message: '_modulepb__.TaskScheduleRequest', *, timeout: 'float | None' = None, deadline: 'Deadline | None' = None, metadata: 'MetadataLike | None' = None) -> '_clientpb__.Task': ...

    async def task_schd_run(message: '_modulepb__.TaskScheduleRequest', *, timeout: 'float | None' = None, deadline: 'Deadline | None' = None, metadata: 'MetadataLike | None' = None) -> '_clientpb__.Task': ...

    async def wmi_query(message: '_modulepb__.WmiQueryRequest', *, timeout: 'float | None' = None, deadline: 'Deadline | None' = None, metadata: 'MetadataLike | None' = None) -> '_clientpb__.Task': ...

    async def wmi_execute(message: '_modulepb__.WmiMethodRequest', *, timeout: 'float | None' = None, deadline: 'Deadline | None' = None, metadata: 'MetadataLike | None' = None) -> '_clientpb__.Task': ...

    async def runas(message: '_modulepb__.RunAsRequest', *, timeout: 'float | None' = None, deadline: 'Deadline | None' = None, metadata: 'MetadataLike | None' = None) -> '_clientpb__.Task': ...

    async def privs(message: '_modulepb__.Request', *, timeout: 'float | None' = None, deadline: 'Deadline | None' = None, metadata: 'MetadataLike | None' = None) -> '_clientpb__.Task': ...

    async def rev_2_self(message: '_modulepb__.Request', *, timeout: 'float | None' = None, deadline: 'Deadline | None' = None, metadata: 'MetadataLike | None' = None) -> '_clientpb__.Task': ...

    async def get_system(message: '_modulepb__.Request', *, timeout: 'float | None' = None, deadline: 'Deadline | None' = None, metadata: 'MetadataLike | None' = None) -> '_clientpb__.Task': ...

    async def pipe_upload(message: '_modulepb__.PipeRequest', *, timeout: 'float | None' = None, deadline: 'Deadline | None' = None, metadata: 'MetadataLike | None' = None) -> '_clientpb__.Task': ...

    async def pipe_read(message: '_modulepb__.PipeRequest', *, timeout: 'float | None' = None, deadline: 'Deadline | None' = None, metadata: 'MetadataLike | None' = None) -> '_clientpb__.Task': ...

    async def pipe_close(message: '_modulepb__.PipeRequest', *, timeout: 'float | None' = None, deadline: 'Deadline | None' = None, metadata: 'MetadataLike | None' = None) -> '_clientpb__.Task': ...

    async def pipe_server(message: '_modulepb__.PipeRequest', *, timeout: 'float | None' = None, deadline: 'Deadline | None' = None, metadata: 'MetadataLike | None' = None) -> '_clientpb__.Task': ...

    async def inline_local(message: '_modulepb__.ExecuteBinary', *, timeout: 'float | None' = None, deadline: 'Deadline | None' = None, metadata: 'MetadataLike | None' = None) -> '_clientpb__.Task': ...

    async def rem_dial(message: '_modulepb__.Request', *, timeout: 'float | None' = None, deadline: 'Deadline | None' = None, metadata: 'MetadataLike | None' = None) -> '_clientpb__.Task': ...

    async def f_fmpeg(message: '_modulepb__.FFmpegRequest', *, timeout: 'float | None' = None, deadline: 'Deadline | None' = None, metadata: 'MetadataLike | None' = None) -> '_clientpb__.Task': ...

    async def exe_2_shellcode(message: '_clientpb__.Exe2Shellcode', *, timeout: 'float | None' = None, deadline: 'Deadline | None' = None, metadata: 'MetadataLike | None' = None) -> '_clientpb__.Bin': ...

    async def dll_2_shellcode(message: '_clientpb__.Dll2Shellcode', *, timeout: 'float | None' = None, deadline: 'Deadline | None' = None, metadata: 'MetadataLike | None' = None) -> '_clientpb__.Bin': ...

    async def list_jobs(message: '_clientpb__.Empty | None' = None, *, timeout: 'float | None' = None, deadline: 'Deadline | None' = None, metadata: 'MetadataLike | None' = None) -> '_clientpb__.Pipelines': ...

    async def get_profiles(message: '_clientpb__.Empty | None' = None, *, timeout: 'float | None' = None, deadline: 'Deadline | None' = None, metadata: 'MetadataLike | None' = None) -> '_clientpb__.Profiles': ...

    async def get_profile_by_name(message: '_clientpb__.Profile', *, timeout: 'float | None' = None, deadline: 'Deadline | None' = None, metadata: 'MetadataLike | None' = None) -> '_clientpb__.Profile': ...

    async def delete_profile(message: '_clientpb__.Profile', *, timeout: 'float | None' = None, deadline: 'Deadline | None' = None, metadata: 'MetadataLike | None' = None) -> '_clientpb__.Empty': ...

    async def update_profile(message: '_clientpb__.Profile', *, timeout: 'float | None' = None, deadline: 'Deadline | None' = None, metadata: 'MetadataLike | None' = None) -> '_clientpb__.Empty': ...

    async def list_artifact(message: '_clientpb__.Empty | None' = None, *, timeout: 'float | None' = None, deadline: 'Deadline | None' = None, metadata: 'MetadataLike | None' = None) -> '_clientpb__.Artifacts': ...

    async def delete_artifact(message: '_clientpb__.Artifact', *, timeout: 'float | None' = None, deadline: 'Deadline | None' = None, metadata: 'MetadataLike | None' = None) -> '_clientpb__.Empty': ...

    async def get_artifact_profile(message: '_clientpb__.Artifact', *, timeout: 'float | None' = None, deadline: 'Deadline | None' = None, metadata: 'MetadataLike | None' = None) -> '_clientpb__.Artifact': ...

    async def get_license_info(message: '_clientpb__.Empty | None' = None, *, timeout: 'float | None' = None, deadline: 'Deadline | None' = None, metadata: 'MetadataLike | None' = None) -> '_clientpb__.LicenseInfo': ...

    async def update_github_config(message: '_clientpb__.GithubActionBuildConfig', *, timeout: 'float | None' = None, deadline: 'Deadline | None' = None, metadata: 'MetadataLike | None' = None) -> '_clientpb__.Empty': ...

    async def get_github_config(message: '_clientpb__.Empty | None' = None, *, timeout: 'float | None' = None, deadline: 'Deadline | None' = None, metadata: 'MetadataLike | None' = None) -> '_clientpb__.GithubActionBuildConfig': ...

    async def update_notify_config(message: '_clientpb__.Notify', *, timeout: 'float | None' = None, deadline: 'Deadline | None' = None, metadata: 'MetadataLike | None' = None) -> '_clientpb__.Empty': ...

    async def get_notify_config(message: '_clientpb__.Empty | None' = None, *, timeout: 'float | None' = None, deadline: 'Deadline | None' = None, metadata: 'MetadataLike | None' = None) -> '_clientpb__.Notify': ...

    async def refresh_config(message: '_clientpb__.Empty | None' = None, *, timeout: 'float | None' = None, deadline: 'Deadline | None' = None, metadata: 'MetadataLike | None' = None) -> '_clientpb__.Empty': ...

    async def delete_certificate(message: '_clientpb__.Cert', *, timeout: 'float | None' = None, deadline: 'Deadline | None' = None, metadata: 'MetadataLike | None' = None) -> '_clientpb__.Empty': ...

    async def update_certificate(message: '_clientpb__.Tls', *, timeout: 'float | None' = None, deadline: 'Deadline | None' = None, metadata: 'MetadataLike | None' = None) -> '_clientpb__.Empty': ...

    async def get_all_certificates(message: '_clientpb__.Empty | None' = None, *, timeout: 'float | None' = None, deadline: 'Deadline | None' = None, metadata: 'MetadataLike | None' = None) -> '_clientpb__.Certs': ...

    async def pty_request(message: '_modulepb__.PtyRequest', *, timeout: 'float | None' = None, deadline: 'Deadline | None' = None, metadata: 'MetadataLike | None' = None) -> '_clientpb__.Task': ...

    async def get_contexts(message: '_clientpb__.Context', *, timeout: 'float | None' = None, deadline: 'Deadline | None' = None, metadata: 'MetadataLike | None' = None) -> '_clientpb__.Contexts': ...

    async def add_context(message: '_clientpb__.Context', *, timeout: 'float | None' = None, deadline: 'Deadline | None' = None, metadata: 'MetadataLike | None' = None) -> '_clientpb__.Empty': ...

    async def add_screen_shot(message: '_clientpb__.Context', *, timeout: 'float | None' = None, deadline: 'Deadline | None' = None, metadata: 'MetadataLike | None' = None) -> '_clientpb__.Empty': ...

    async def add_credential(message: '_clientpb__.Context', *, timeout: 'float | None' = None, deadline: 'Deadline | None' = None, metadata: 'MetadataLike | None' = None) -> '_clientpb__.Empty': ...

    async def add_keylogger(message: '_clientpb__.Context', *, timeout: 'float | None' = None, deadline: 'Deadline | None' = None, metadata: 'MetadataLike | None' = None) -> '_clientpb__.Empty': ...

    async def add_port(message: '_clientpb__.Context', *, timeout: 'float | None' = None, deadline: 'Deadline | None' = None, metadata: 'MetadataLike | None' = None) -> '_clientpb__.Empty': ...

    async def add_upload(message: '_clientpb__.Context', *, timeout: 'float | None' = None, deadline: 'Deadline | None' = None, metadata: 'MetadataLike | None' = None) -> '_clientpb__.Empty': ...

    async def add_download(message: '_clientpb__.Context', *, timeout: 'float | None' = None, deadline: 'Deadline | None' = None, metadata: 'MetadataLike | None' = None) -> '_clientpb__.Empty': ...


class SessionManager:
    def __init__(self: Any, client: 'MaliceClient') -> Any: ...
    async def list_sessions(self: Any, alive_only: bool = False) -> Dict[str, Session]: ...
    async def get_session(self: Any, session_id: str) -> Optional[MaliceSession]: ...
    async def get_session_by_name(self: Any, name: str) -> Optional[MaliceSession]: ...
    async def get_alive_sessions(self: Any) -> List[MaliceSession]: ...
    async def interactive_session(self: Any) -> Optional[MaliceSession]: ...